// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/HeartBeatRPC.proto

package pipe.work;

public final class HeartBeatRPC {
  private HeartBeatRPC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeartBeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartBeat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 term = 1;</code>
     */
    boolean hasTerm();
    /**
     * <code>required int32 term = 1;</code>
     */
    int getTerm();

    /**
     * <code>required int32 leaderId = 2;</code>
     */
    boolean hasLeaderId();
    /**
     * <code>required int32 leaderId = 2;</code>
     */
    int getLeaderId();

    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    boolean hasTimeStampOnLatestUpdate();
    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    long getTimeStampOnLatestUpdate();
  }
  /**
   * Protobuf type {@code HeartBeat}
   */
  public  static final class HeartBeat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HeartBeat)
      HeartBeatOrBuilder {
    // Use HeartBeat.newBuilder() to construct.
    private HeartBeat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartBeat() {
      term_ = 0;
      leaderId_ = 0;
      timeStampOnLatestUpdate_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              term_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              leaderId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timeStampOnLatestUpdate_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pipe.work.HeartBeatRPC.internal_static_HeartBeat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pipe.work.HeartBeatRPC.internal_static_HeartBeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pipe.work.HeartBeatRPC.HeartBeat.class, pipe.work.HeartBeatRPC.HeartBeat.Builder.class);
    }

    private int bitField0_;
    public static final int TERM_FIELD_NUMBER = 1;
    private int term_;
    /**
     * <code>required int32 term = 1;</code>
     */
    public boolean hasTerm() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 term = 1;</code>
     */
    public int getTerm() {
      return term_;
    }

    public static final int LEADERID_FIELD_NUMBER = 2;
    private int leaderId_;
    /**
     * <code>required int32 leaderId = 2;</code>
     */
    public boolean hasLeaderId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 leaderId = 2;</code>
     */
    public int getLeaderId() {
      return leaderId_;
    }

    public static final int TIMESTAMPONLATESTUPDATE_FIELD_NUMBER = 3;
    private long timeStampOnLatestUpdate_;
    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    public boolean hasTimeStampOnLatestUpdate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    public long getTimeStampOnLatestUpdate() {
      return timeStampOnLatestUpdate_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTerm()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLeaderId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeStampOnLatestUpdate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, leaderId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, timeStampOnLatestUpdate_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, leaderId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timeStampOnLatestUpdate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pipe.work.HeartBeatRPC.HeartBeat)) {
        return super.equals(obj);
      }
      pipe.work.HeartBeatRPC.HeartBeat other = (pipe.work.HeartBeatRPC.HeartBeat) obj;

      boolean result = true;
      result = result && (hasTerm() == other.hasTerm());
      if (hasTerm()) {
        result = result && (getTerm()
            == other.getTerm());
      }
      result = result && (hasLeaderId() == other.hasLeaderId());
      if (hasLeaderId()) {
        result = result && (getLeaderId()
            == other.getLeaderId());
      }
      result = result && (hasTimeStampOnLatestUpdate() == other.hasTimeStampOnLatestUpdate());
      if (hasTimeStampOnLatestUpdate()) {
        result = result && (getTimeStampOnLatestUpdate()
            == other.getTimeStampOnLatestUpdate());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTerm()) {
        hash = (37 * hash) + TERM_FIELD_NUMBER;
        hash = (53 * hash) + getTerm();
      }
      if (hasLeaderId()) {
        hash = (37 * hash) + LEADERID_FIELD_NUMBER;
        hash = (53 * hash) + getLeaderId();
      }
      if (hasTimeStampOnLatestUpdate()) {
        hash = (37 * hash) + TIMESTAMPONLATESTUPDATE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimeStampOnLatestUpdate());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pipe.work.HeartBeatRPC.HeartBeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.work.HeartBeatRPC.HeartBeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.work.HeartBeatRPC.HeartBeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.work.HeartBeatRPC.HeartBeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.work.HeartBeatRPC.HeartBeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.work.HeartBeatRPC.HeartBeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.work.HeartBeatRPC.HeartBeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pipe.work.HeartBeatRPC.HeartBeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.work.HeartBeatRPC.HeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.work.HeartBeatRPC.HeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pipe.work.HeartBeatRPC.HeartBeat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeartBeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartBeat)
        pipe.work.HeartBeatRPC.HeartBeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pipe.work.HeartBeatRPC.internal_static_HeartBeat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pipe.work.HeartBeatRPC.internal_static_HeartBeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pipe.work.HeartBeatRPC.HeartBeat.class, pipe.work.HeartBeatRPC.HeartBeat.Builder.class);
      }

      // Construct using pipe.work.HeartBeatRPC.HeartBeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        term_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        leaderId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        timeStampOnLatestUpdate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pipe.work.HeartBeatRPC.internal_static_HeartBeat_descriptor;
      }

      public pipe.work.HeartBeatRPC.HeartBeat getDefaultInstanceForType() {
        return pipe.work.HeartBeatRPC.HeartBeat.getDefaultInstance();
      }

      public pipe.work.HeartBeatRPC.HeartBeat build() {
        pipe.work.HeartBeatRPC.HeartBeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pipe.work.HeartBeatRPC.HeartBeat buildPartial() {
        pipe.work.HeartBeatRPC.HeartBeat result = new pipe.work.HeartBeatRPC.HeartBeat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.term_ = term_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.leaderId_ = leaderId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timeStampOnLatestUpdate_ = timeStampOnLatestUpdate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pipe.work.HeartBeatRPC.HeartBeat) {
          return mergeFrom((pipe.work.HeartBeatRPC.HeartBeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pipe.work.HeartBeatRPC.HeartBeat other) {
        if (other == pipe.work.HeartBeatRPC.HeartBeat.getDefaultInstance()) return this;
        if (other.hasTerm()) {
          setTerm(other.getTerm());
        }
        if (other.hasLeaderId()) {
          setLeaderId(other.getLeaderId());
        }
        if (other.hasTimeStampOnLatestUpdate()) {
          setTimeStampOnLatestUpdate(other.getTimeStampOnLatestUpdate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTerm()) {
          return false;
        }
        if (!hasLeaderId()) {
          return false;
        }
        if (!hasTimeStampOnLatestUpdate()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pipe.work.HeartBeatRPC.HeartBeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pipe.work.HeartBeatRPC.HeartBeat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int term_ ;
      /**
       * <code>required int32 term = 1;</code>
       */
      public boolean hasTerm() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public int getTerm() {
        return term_;
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public Builder setTerm(int value) {
        bitField0_ |= 0x00000001;
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public Builder clearTerm() {
        bitField0_ = (bitField0_ & ~0x00000001);
        term_ = 0;
        onChanged();
        return this;
      }

      private int leaderId_ ;
      /**
       * <code>required int32 leaderId = 2;</code>
       */
      public boolean hasLeaderId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 leaderId = 2;</code>
       */
      public int getLeaderId() {
        return leaderId_;
      }
      /**
       * <code>required int32 leaderId = 2;</code>
       */
      public Builder setLeaderId(int value) {
        bitField0_ |= 0x00000002;
        leaderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 leaderId = 2;</code>
       */
      public Builder clearLeaderId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        leaderId_ = 0;
        onChanged();
        return this;
      }

      private long timeStampOnLatestUpdate_ ;
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public boolean hasTimeStampOnLatestUpdate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public long getTimeStampOnLatestUpdate() {
        return timeStampOnLatestUpdate_;
      }
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public Builder setTimeStampOnLatestUpdate(long value) {
        bitField0_ |= 0x00000004;
        timeStampOnLatestUpdate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public Builder clearTimeStampOnLatestUpdate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timeStampOnLatestUpdate_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HeartBeat)
    }

    // @@protoc_insertion_point(class_scope:HeartBeat)
    private static final pipe.work.HeartBeatRPC.HeartBeat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pipe.work.HeartBeatRPC.HeartBeat();
    }

    public static pipe.work.HeartBeatRPC.HeartBeat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<HeartBeat>
        PARSER = new com.google.protobuf.AbstractParser<HeartBeat>() {
      public HeartBeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HeartBeat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartBeat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeat> getParserForType() {
      return PARSER;
    }

    public pipe.work.HeartBeatRPC.HeartBeat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeartBeatResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartBeatResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 term = 1;</code>
     */
    boolean hasTerm();
    /**
     * <code>required int32 term = 1;</code>
     */
    int getTerm();

    /**
     * <code>required int32 nodeId = 2;</code>
     */
    boolean hasNodeId();
    /**
     * <code>required int32 nodeId = 2;</code>
     */
    int getNodeId();

    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    boolean hasTimeStampOnLatestUpdate();
    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    long getTimeStampOnLatestUpdate();
  }
  /**
   * Protobuf type {@code HeartBeatResponse}
   */
  public  static final class HeartBeatResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HeartBeatResponse)
      HeartBeatResponseOrBuilder {
    // Use HeartBeatResponse.newBuilder() to construct.
    private HeartBeatResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartBeatResponse() {
      term_ = 0;
      nodeId_ = 0;
      timeStampOnLatestUpdate_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeatResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              term_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              nodeId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timeStampOnLatestUpdate_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pipe.work.HeartBeatRPC.internal_static_HeartBeatResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pipe.work.HeartBeatRPC.internal_static_HeartBeatResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pipe.work.HeartBeatRPC.HeartBeatResponse.class, pipe.work.HeartBeatRPC.HeartBeatResponse.Builder.class);
    }

    /**
     * Protobuf enum {@code HeartBeatResponse.IsAlive}
     */
    public enum IsAlive
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>YES = 1;</code>
       */
      YES(1),
      /**
       * <code>NO = 2;</code>
       */
      NO(2),
      ;

      /**
       * <code>YES = 1;</code>
       */
      public static final int YES_VALUE = 1;
      /**
       * <code>NO = 2;</code>
       */
      public static final int NO_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static IsAlive valueOf(int value) {
        return forNumber(value);
      }

      public static IsAlive forNumber(int value) {
        switch (value) {
          case 1: return YES;
          case 2: return NO;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<IsAlive>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          IsAlive> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<IsAlive>() {
              public IsAlive findValueByNumber(int number) {
                return IsAlive.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return pipe.work.HeartBeatRPC.HeartBeatResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final IsAlive[] VALUES = values();

      public static IsAlive valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private IsAlive(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:HeartBeatResponse.IsAlive)
    }

    private int bitField0_;
    public static final int TERM_FIELD_NUMBER = 1;
    private int term_;
    /**
     * <code>required int32 term = 1;</code>
     */
    public boolean hasTerm() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 term = 1;</code>
     */
    public int getTerm() {
      return term_;
    }

    public static final int NODEID_FIELD_NUMBER = 2;
    private int nodeId_;
    /**
     * <code>required int32 nodeId = 2;</code>
     */
    public boolean hasNodeId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 nodeId = 2;</code>
     */
    public int getNodeId() {
      return nodeId_;
    }

    public static final int TIMESTAMPONLATESTUPDATE_FIELD_NUMBER = 3;
    private long timeStampOnLatestUpdate_;
    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    public boolean hasTimeStampOnLatestUpdate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    public long getTimeStampOnLatestUpdate() {
      return timeStampOnLatestUpdate_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTerm()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNodeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeStampOnLatestUpdate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, nodeId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, timeStampOnLatestUpdate_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, nodeId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timeStampOnLatestUpdate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pipe.work.HeartBeatRPC.HeartBeatResponse)) {
        return super.equals(obj);
      }
      pipe.work.HeartBeatRPC.HeartBeatResponse other = (pipe.work.HeartBeatRPC.HeartBeatResponse) obj;

      boolean result = true;
      result = result && (hasTerm() == other.hasTerm());
      if (hasTerm()) {
        result = result && (getTerm()
            == other.getTerm());
      }
      result = result && (hasNodeId() == other.hasNodeId());
      if (hasNodeId()) {
        result = result && (getNodeId()
            == other.getNodeId());
      }
      result = result && (hasTimeStampOnLatestUpdate() == other.hasTimeStampOnLatestUpdate());
      if (hasTimeStampOnLatestUpdate()) {
        result = result && (getTimeStampOnLatestUpdate()
            == other.getTimeStampOnLatestUpdate());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTerm()) {
        hash = (37 * hash) + TERM_FIELD_NUMBER;
        hash = (53 * hash) + getTerm();
      }
      if (hasNodeId()) {
        hash = (37 * hash) + NODEID_FIELD_NUMBER;
        hash = (53 * hash) + getNodeId();
      }
      if (hasTimeStampOnLatestUpdate()) {
        hash = (37 * hash) + TIMESTAMPONLATESTUPDATE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimeStampOnLatestUpdate());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pipe.work.HeartBeatRPC.HeartBeatResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.work.HeartBeatRPC.HeartBeatResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.work.HeartBeatRPC.HeartBeatResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.work.HeartBeatRPC.HeartBeatResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.work.HeartBeatRPC.HeartBeatResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.work.HeartBeatRPC.HeartBeatResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.work.HeartBeatRPC.HeartBeatResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pipe.work.HeartBeatRPC.HeartBeatResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.work.HeartBeatRPC.HeartBeatResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.work.HeartBeatRPC.HeartBeatResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pipe.work.HeartBeatRPC.HeartBeatResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeartBeatResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartBeatResponse)
        pipe.work.HeartBeatRPC.HeartBeatResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pipe.work.HeartBeatRPC.internal_static_HeartBeatResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pipe.work.HeartBeatRPC.internal_static_HeartBeatResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pipe.work.HeartBeatRPC.HeartBeatResponse.class, pipe.work.HeartBeatRPC.HeartBeatResponse.Builder.class);
      }

      // Construct using pipe.work.HeartBeatRPC.HeartBeatResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        term_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        timeStampOnLatestUpdate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pipe.work.HeartBeatRPC.internal_static_HeartBeatResponse_descriptor;
      }

      public pipe.work.HeartBeatRPC.HeartBeatResponse getDefaultInstanceForType() {
        return pipe.work.HeartBeatRPC.HeartBeatResponse.getDefaultInstance();
      }

      public pipe.work.HeartBeatRPC.HeartBeatResponse build() {
        pipe.work.HeartBeatRPC.HeartBeatResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pipe.work.HeartBeatRPC.HeartBeatResponse buildPartial() {
        pipe.work.HeartBeatRPC.HeartBeatResponse result = new pipe.work.HeartBeatRPC.HeartBeatResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.term_ = term_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nodeId_ = nodeId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timeStampOnLatestUpdate_ = timeStampOnLatestUpdate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pipe.work.HeartBeatRPC.HeartBeatResponse) {
          return mergeFrom((pipe.work.HeartBeatRPC.HeartBeatResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pipe.work.HeartBeatRPC.HeartBeatResponse other) {
        if (other == pipe.work.HeartBeatRPC.HeartBeatResponse.getDefaultInstance()) return this;
        if (other.hasTerm()) {
          setTerm(other.getTerm());
        }
        if (other.hasNodeId()) {
          setNodeId(other.getNodeId());
        }
        if (other.hasTimeStampOnLatestUpdate()) {
          setTimeStampOnLatestUpdate(other.getTimeStampOnLatestUpdate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTerm()) {
          return false;
        }
        if (!hasNodeId()) {
          return false;
        }
        if (!hasTimeStampOnLatestUpdate()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pipe.work.HeartBeatRPC.HeartBeatResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pipe.work.HeartBeatRPC.HeartBeatResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int term_ ;
      /**
       * <code>required int32 term = 1;</code>
       */
      public boolean hasTerm() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public int getTerm() {
        return term_;
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public Builder setTerm(int value) {
        bitField0_ |= 0x00000001;
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public Builder clearTerm() {
        bitField0_ = (bitField0_ & ~0x00000001);
        term_ = 0;
        onChanged();
        return this;
      }

      private int nodeId_ ;
      /**
       * <code>required int32 nodeId = 2;</code>
       */
      public boolean hasNodeId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 nodeId = 2;</code>
       */
      public int getNodeId() {
        return nodeId_;
      }
      /**
       * <code>required int32 nodeId = 2;</code>
       */
      public Builder setNodeId(int value) {
        bitField0_ |= 0x00000002;
        nodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 nodeId = 2;</code>
       */
      public Builder clearNodeId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nodeId_ = 0;
        onChanged();
        return this;
      }

      private long timeStampOnLatestUpdate_ ;
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public boolean hasTimeStampOnLatestUpdate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public long getTimeStampOnLatestUpdate() {
        return timeStampOnLatestUpdate_;
      }
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public Builder setTimeStampOnLatestUpdate(long value) {
        bitField0_ |= 0x00000004;
        timeStampOnLatestUpdate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public Builder clearTimeStampOnLatestUpdate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timeStampOnLatestUpdate_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HeartBeatResponse)
    }

    // @@protoc_insertion_point(class_scope:HeartBeatResponse)
    private static final pipe.work.HeartBeatRPC.HeartBeatResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pipe.work.HeartBeatRPC.HeartBeatResponse();
    }

    public static pipe.work.HeartBeatRPC.HeartBeatResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<HeartBeatResponse>
        PARSER = new com.google.protobuf.AbstractParser<HeartBeatResponse>() {
      public HeartBeatResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HeartBeatResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartBeatResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeatResponse> getParserForType() {
      return PARSER;
    }

    public pipe.work.HeartBeatRPC.HeartBeatResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeartBeatPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartBeatPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 unixTimestamp = 1;</code>
     */
    boolean hasUnixTimestamp();
    /**
     * <code>required int64 unixTimestamp = 1;</code>
     */
    long getUnixTimestamp();

    /**
     * <code>optional .HeartBeat heartbeat = 2;</code>
     */
    boolean hasHeartbeat();
    /**
     * <code>optional .HeartBeat heartbeat = 2;</code>
     */
    pipe.work.HeartBeatRPC.HeartBeat getHeartbeat();
    /**
     * <code>optional .HeartBeat heartbeat = 2;</code>
     */
    pipe.work.HeartBeatRPC.HeartBeatOrBuilder getHeartbeatOrBuilder();

    /**
     * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
     */
    boolean hasHeartBeatResponse();
    /**
     * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
     */
    pipe.work.HeartBeatRPC.HeartBeatResponse getHeartBeatResponse();
    /**
     * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
     */
    pipe.work.HeartBeatRPC.HeartBeatResponseOrBuilder getHeartBeatResponseOrBuilder();

    public pipe.work.HeartBeatRPC.HeartBeatPacket.PayloadCase getPayloadCase();
  }
  /**
   * Protobuf type {@code HeartBeatPacket}
   */
  public  static final class HeartBeatPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HeartBeatPacket)
      HeartBeatPacketOrBuilder {
    // Use HeartBeatPacket.newBuilder() to construct.
    private HeartBeatPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartBeatPacket() {
      unixTimestamp_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeatPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              unixTimestamp_ = input.readInt64();
              break;
            }
            case 18: {
              pipe.work.HeartBeatRPC.HeartBeat.Builder subBuilder = null;
              if (payloadCase_ == 2) {
                subBuilder = ((pipe.work.HeartBeatRPC.HeartBeat) payload_).toBuilder();
              }
              payload_ =
                  input.readMessage(pipe.work.HeartBeatRPC.HeartBeat.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((pipe.work.HeartBeatRPC.HeartBeat) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 2;
              break;
            }
            case 26: {
              pipe.work.HeartBeatRPC.HeartBeatResponse.Builder subBuilder = null;
              if (payloadCase_ == 3) {
                subBuilder = ((pipe.work.HeartBeatRPC.HeartBeatResponse) payload_).toBuilder();
              }
              payload_ =
                  input.readMessage(pipe.work.HeartBeatRPC.HeartBeatResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((pipe.work.HeartBeatRPC.HeartBeatResponse) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 3;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pipe.work.HeartBeatRPC.internal_static_HeartBeatPacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pipe.work.HeartBeatRPC.internal_static_HeartBeatPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pipe.work.HeartBeatRPC.HeartBeatPacket.class, pipe.work.HeartBeatRPC.HeartBeatPacket.Builder.class);
    }

    private int bitField0_;
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite {
      HEARTBEAT(2),
      HEARTBEATRESPONSE(3),
      PAYLOAD_NOT_SET(0);
      private final int value;
      private PayloadCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PayloadCase valueOf(int value) {
        return forNumber(value);
      }

      public static PayloadCase forNumber(int value) {
        switch (value) {
          case 2: return HEARTBEAT;
          case 3: return HEARTBEATRESPONSE;
          case 0: return PAYLOAD_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PayloadCase
    getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public static final int UNIXTIMESTAMP_FIELD_NUMBER = 1;
    private long unixTimestamp_;
    /**
     * <code>required int64 unixTimestamp = 1;</code>
     */
    public boolean hasUnixTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 unixTimestamp = 1;</code>
     */
    public long getUnixTimestamp() {
      return unixTimestamp_;
    }

    public static final int HEARTBEAT_FIELD_NUMBER = 2;
    /**
     * <code>optional .HeartBeat heartbeat = 2;</code>
     */
    public boolean hasHeartbeat() {
      return payloadCase_ == 2;
    }
    /**
     * <code>optional .HeartBeat heartbeat = 2;</code>
     */
    public pipe.work.HeartBeatRPC.HeartBeat getHeartbeat() {
      if (payloadCase_ == 2) {
         return (pipe.work.HeartBeatRPC.HeartBeat) payload_;
      }
      return pipe.work.HeartBeatRPC.HeartBeat.getDefaultInstance();
    }
    /**
     * <code>optional .HeartBeat heartbeat = 2;</code>
     */
    public pipe.work.HeartBeatRPC.HeartBeatOrBuilder getHeartbeatOrBuilder() {
      if (payloadCase_ == 2) {
         return (pipe.work.HeartBeatRPC.HeartBeat) payload_;
      }
      return pipe.work.HeartBeatRPC.HeartBeat.getDefaultInstance();
    }

    public static final int HEARTBEATRESPONSE_FIELD_NUMBER = 3;
    /**
     * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
     */
    public boolean hasHeartBeatResponse() {
      return payloadCase_ == 3;
    }
    /**
     * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
     */
    public pipe.work.HeartBeatRPC.HeartBeatResponse getHeartBeatResponse() {
      if (payloadCase_ == 3) {
         return (pipe.work.HeartBeatRPC.HeartBeatResponse) payload_;
      }
      return pipe.work.HeartBeatRPC.HeartBeatResponse.getDefaultInstance();
    }
    /**
     * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
     */
    public pipe.work.HeartBeatRPC.HeartBeatResponseOrBuilder getHeartBeatResponseOrBuilder() {
      if (payloadCase_ == 3) {
         return (pipe.work.HeartBeatRPC.HeartBeatResponse) payload_;
      }
      return pipe.work.HeartBeatRPC.HeartBeatResponse.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUnixTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasHeartbeat()) {
        if (!getHeartbeat().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasHeartBeatResponse()) {
        if (!getHeartBeatResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, unixTimestamp_);
      }
      if (payloadCase_ == 2) {
        output.writeMessage(2, (pipe.work.HeartBeatRPC.HeartBeat) payload_);
      }
      if (payloadCase_ == 3) {
        output.writeMessage(3, (pipe.work.HeartBeatRPC.HeartBeatResponse) payload_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, unixTimestamp_);
      }
      if (payloadCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (pipe.work.HeartBeatRPC.HeartBeat) payload_);
      }
      if (payloadCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (pipe.work.HeartBeatRPC.HeartBeatResponse) payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pipe.work.HeartBeatRPC.HeartBeatPacket)) {
        return super.equals(obj);
      }
      pipe.work.HeartBeatRPC.HeartBeatPacket other = (pipe.work.HeartBeatRPC.HeartBeatPacket) obj;

      boolean result = true;
      result = result && (hasUnixTimestamp() == other.hasUnixTimestamp());
      if (hasUnixTimestamp()) {
        result = result && (getUnixTimestamp()
            == other.getUnixTimestamp());
      }
      result = result && getPayloadCase().equals(
          other.getPayloadCase());
      if (!result) return false;
      switch (payloadCase_) {
        case 2:
          result = result && getHeartbeat()
              .equals(other.getHeartbeat());
          break;
        case 3:
          result = result && getHeartBeatResponse()
              .equals(other.getHeartBeatResponse());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUnixTimestamp()) {
        hash = (37 * hash) + UNIXTIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUnixTimestamp());
      }
      switch (payloadCase_) {
        case 2:
          hash = (37 * hash) + HEARTBEAT_FIELD_NUMBER;
          hash = (53 * hash) + getHeartbeat().hashCode();
          break;
        case 3:
          hash = (37 * hash) + HEARTBEATRESPONSE_FIELD_NUMBER;
          hash = (53 * hash) + getHeartBeatResponse().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pipe.work.HeartBeatRPC.HeartBeatPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.work.HeartBeatRPC.HeartBeatPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.work.HeartBeatRPC.HeartBeatPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.work.HeartBeatRPC.HeartBeatPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.work.HeartBeatRPC.HeartBeatPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.work.HeartBeatRPC.HeartBeatPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.work.HeartBeatRPC.HeartBeatPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pipe.work.HeartBeatRPC.HeartBeatPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.work.HeartBeatRPC.HeartBeatPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.work.HeartBeatRPC.HeartBeatPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pipe.work.HeartBeatRPC.HeartBeatPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeartBeatPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartBeatPacket)
        pipe.work.HeartBeatRPC.HeartBeatPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pipe.work.HeartBeatRPC.internal_static_HeartBeatPacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pipe.work.HeartBeatRPC.internal_static_HeartBeatPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pipe.work.HeartBeatRPC.HeartBeatPacket.class, pipe.work.HeartBeatRPC.HeartBeatPacket.Builder.class);
      }

      // Construct using pipe.work.HeartBeatRPC.HeartBeatPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        unixTimestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        payloadCase_ = 0;
        payload_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pipe.work.HeartBeatRPC.internal_static_HeartBeatPacket_descriptor;
      }

      public pipe.work.HeartBeatRPC.HeartBeatPacket getDefaultInstanceForType() {
        return pipe.work.HeartBeatRPC.HeartBeatPacket.getDefaultInstance();
      }

      public pipe.work.HeartBeatRPC.HeartBeatPacket build() {
        pipe.work.HeartBeatRPC.HeartBeatPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pipe.work.HeartBeatRPC.HeartBeatPacket buildPartial() {
        pipe.work.HeartBeatRPC.HeartBeatPacket result = new pipe.work.HeartBeatRPC.HeartBeatPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.unixTimestamp_ = unixTimestamp_;
        if (payloadCase_ == 2) {
          if (heartbeatBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = heartbeatBuilder_.build();
          }
        }
        if (payloadCase_ == 3) {
          if (heartBeatResponseBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = heartBeatResponseBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.payloadCase_ = payloadCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pipe.work.HeartBeatRPC.HeartBeatPacket) {
          return mergeFrom((pipe.work.HeartBeatRPC.HeartBeatPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pipe.work.HeartBeatRPC.HeartBeatPacket other) {
        if (other == pipe.work.HeartBeatRPC.HeartBeatPacket.getDefaultInstance()) return this;
        if (other.hasUnixTimestamp()) {
          setUnixTimestamp(other.getUnixTimestamp());
        }
        switch (other.getPayloadCase()) {
          case HEARTBEAT: {
            mergeHeartbeat(other.getHeartbeat());
            break;
          }
          case HEARTBEATRESPONSE: {
            mergeHeartBeatResponse(other.getHeartBeatResponse());
            break;
          }
          case PAYLOAD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUnixTimestamp()) {
          return false;
        }
        if (hasHeartbeat()) {
          if (!getHeartbeat().isInitialized()) {
            return false;
          }
        }
        if (hasHeartBeatResponse()) {
          if (!getHeartBeatResponse().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pipe.work.HeartBeatRPC.HeartBeatPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pipe.work.HeartBeatRPC.HeartBeatPacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int payloadCase_ = 0;
      private java.lang.Object payload_;
      public PayloadCase
          getPayloadCase() {
        return PayloadCase.forNumber(
            payloadCase_);
      }

      public Builder clearPayload() {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private long unixTimestamp_ ;
      /**
       * <code>required int64 unixTimestamp = 1;</code>
       */
      public boolean hasUnixTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 unixTimestamp = 1;</code>
       */
      public long getUnixTimestamp() {
        return unixTimestamp_;
      }
      /**
       * <code>required int64 unixTimestamp = 1;</code>
       */
      public Builder setUnixTimestamp(long value) {
        bitField0_ |= 0x00000001;
        unixTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 unixTimestamp = 1;</code>
       */
      public Builder clearUnixTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        unixTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.work.HeartBeatRPC.HeartBeat, pipe.work.HeartBeatRPC.HeartBeat.Builder, pipe.work.HeartBeatRPC.HeartBeatOrBuilder> heartbeatBuilder_;
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      public boolean hasHeartbeat() {
        return payloadCase_ == 2;
      }
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      public pipe.work.HeartBeatRPC.HeartBeat getHeartbeat() {
        if (heartbeatBuilder_ == null) {
          if (payloadCase_ == 2) {
            return (pipe.work.HeartBeatRPC.HeartBeat) payload_;
          }
          return pipe.work.HeartBeatRPC.HeartBeat.getDefaultInstance();
        } else {
          if (payloadCase_ == 2) {
            return heartbeatBuilder_.getMessage();
          }
          return pipe.work.HeartBeatRPC.HeartBeat.getDefaultInstance();
        }
      }
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      public Builder setHeartbeat(pipe.work.HeartBeatRPC.HeartBeat value) {
        if (heartbeatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          heartbeatBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      public Builder setHeartbeat(
          pipe.work.HeartBeatRPC.HeartBeat.Builder builderForValue) {
        if (heartbeatBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          heartbeatBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      public Builder mergeHeartbeat(pipe.work.HeartBeatRPC.HeartBeat value) {
        if (heartbeatBuilder_ == null) {
          if (payloadCase_ == 2 &&
              payload_ != pipe.work.HeartBeatRPC.HeartBeat.getDefaultInstance()) {
            payload_ = pipe.work.HeartBeatRPC.HeartBeat.newBuilder((pipe.work.HeartBeatRPC.HeartBeat) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 2) {
            heartbeatBuilder_.mergeFrom(value);
          }
          heartbeatBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      public Builder clearHeartbeat() {
        if (heartbeatBuilder_ == null) {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
          }
          heartbeatBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      public pipe.work.HeartBeatRPC.HeartBeat.Builder getHeartbeatBuilder() {
        return getHeartbeatFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      public pipe.work.HeartBeatRPC.HeartBeatOrBuilder getHeartbeatOrBuilder() {
        if ((payloadCase_ == 2) && (heartbeatBuilder_ != null)) {
          return heartbeatBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 2) {
            return (pipe.work.HeartBeatRPC.HeartBeat) payload_;
          }
          return pipe.work.HeartBeatRPC.HeartBeat.getDefaultInstance();
        }
      }
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.work.HeartBeatRPC.HeartBeat, pipe.work.HeartBeatRPC.HeartBeat.Builder, pipe.work.HeartBeatRPC.HeartBeatOrBuilder> 
          getHeartbeatFieldBuilder() {
        if (heartbeatBuilder_ == null) {
          if (!(payloadCase_ == 2)) {
            payload_ = pipe.work.HeartBeatRPC.HeartBeat.getDefaultInstance();
          }
          heartbeatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pipe.work.HeartBeatRPC.HeartBeat, pipe.work.HeartBeatRPC.HeartBeat.Builder, pipe.work.HeartBeatRPC.HeartBeatOrBuilder>(
                  (pipe.work.HeartBeatRPC.HeartBeat) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 2;
        onChanged();;
        return heartbeatBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.work.HeartBeatRPC.HeartBeatResponse, pipe.work.HeartBeatRPC.HeartBeatResponse.Builder, pipe.work.HeartBeatRPC.HeartBeatResponseOrBuilder> heartBeatResponseBuilder_;
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      public boolean hasHeartBeatResponse() {
        return payloadCase_ == 3;
      }
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      public pipe.work.HeartBeatRPC.HeartBeatResponse getHeartBeatResponse() {
        if (heartBeatResponseBuilder_ == null) {
          if (payloadCase_ == 3) {
            return (pipe.work.HeartBeatRPC.HeartBeatResponse) payload_;
          }
          return pipe.work.HeartBeatRPC.HeartBeatResponse.getDefaultInstance();
        } else {
          if (payloadCase_ == 3) {
            return heartBeatResponseBuilder_.getMessage();
          }
          return pipe.work.HeartBeatRPC.HeartBeatResponse.getDefaultInstance();
        }
      }
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      public Builder setHeartBeatResponse(pipe.work.HeartBeatRPC.HeartBeatResponse value) {
        if (heartBeatResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          heartBeatResponseBuilder_.setMessage(value);
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      public Builder setHeartBeatResponse(
          pipe.work.HeartBeatRPC.HeartBeatResponse.Builder builderForValue) {
        if (heartBeatResponseBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          heartBeatResponseBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      public Builder mergeHeartBeatResponse(pipe.work.HeartBeatRPC.HeartBeatResponse value) {
        if (heartBeatResponseBuilder_ == null) {
          if (payloadCase_ == 3 &&
              payload_ != pipe.work.HeartBeatRPC.HeartBeatResponse.getDefaultInstance()) {
            payload_ = pipe.work.HeartBeatRPC.HeartBeatResponse.newBuilder((pipe.work.HeartBeatRPC.HeartBeatResponse) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 3) {
            heartBeatResponseBuilder_.mergeFrom(value);
          }
          heartBeatResponseBuilder_.setMessage(value);
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      public Builder clearHeartBeatResponse() {
        if (heartBeatResponseBuilder_ == null) {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
          }
          heartBeatResponseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      public pipe.work.HeartBeatRPC.HeartBeatResponse.Builder getHeartBeatResponseBuilder() {
        return getHeartBeatResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      public pipe.work.HeartBeatRPC.HeartBeatResponseOrBuilder getHeartBeatResponseOrBuilder() {
        if ((payloadCase_ == 3) && (heartBeatResponseBuilder_ != null)) {
          return heartBeatResponseBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 3) {
            return (pipe.work.HeartBeatRPC.HeartBeatResponse) payload_;
          }
          return pipe.work.HeartBeatRPC.HeartBeatResponse.getDefaultInstance();
        }
      }
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.work.HeartBeatRPC.HeartBeatResponse, pipe.work.HeartBeatRPC.HeartBeatResponse.Builder, pipe.work.HeartBeatRPC.HeartBeatResponseOrBuilder> 
          getHeartBeatResponseFieldBuilder() {
        if (heartBeatResponseBuilder_ == null) {
          if (!(payloadCase_ == 3)) {
            payload_ = pipe.work.HeartBeatRPC.HeartBeatResponse.getDefaultInstance();
          }
          heartBeatResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pipe.work.HeartBeatRPC.HeartBeatResponse, pipe.work.HeartBeatRPC.HeartBeatResponse.Builder, pipe.work.HeartBeatRPC.HeartBeatResponseOrBuilder>(
                  (pipe.work.HeartBeatRPC.HeartBeatResponse) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 3;
        onChanged();;
        return heartBeatResponseBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HeartBeatPacket)
    }

    // @@protoc_insertion_point(class_scope:HeartBeatPacket)
    private static final pipe.work.HeartBeatRPC.HeartBeatPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pipe.work.HeartBeatRPC.HeartBeatPacket();
    }

    public static pipe.work.HeartBeatRPC.HeartBeatPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<HeartBeatPacket>
        PARSER = new com.google.protobuf.AbstractParser<HeartBeatPacket>() {
      public HeartBeatPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HeartBeatPacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartBeatPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeatPacket> getParserForType() {
      return PARSER;
    }

    public pipe.work.HeartBeatRPC.HeartBeatPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeatResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeatResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeatPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeatPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034resources/HeartBeatRPC.proto\"L\n\tHeartB" +
      "eat\022\014\n\004term\030\001 \002(\005\022\020\n\010leaderId\030\002 \002(\005\022\037\n\027t" +
      "imeStampOnLatestUpdate\030\003 \002(\003\"n\n\021HeartBea" +
      "tResponse\022\014\n\004term\030\001 \002(\005\022\016\n\006nodeId\030\002 \002(\005\022" +
      "\037\n\027timeStampOnLatestUpdate\030\003 \002(\003\"\032\n\007IsAl" +
      "ive\022\007\n\003YES\020\001\022\006\n\002NO\020\002\"\205\001\n\017HeartBeatPacket" +
      "\022\025\n\runixTimestamp\030\001 \002(\003\022\037\n\theartbeat\030\002 \001" +
      "(\0132\n.HeartBeatH\000\022/\n\021heartBeatResponse\030\003 " +
      "\001(\0132\022.HeartBeatResponseH\000B\t\n\007payloadB\013\n\t" +
      "pipe.work"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HeartBeat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HeartBeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeat_descriptor,
        new java.lang.String[] { "Term", "LeaderId", "TimeStampOnLatestUpdate", });
    internal_static_HeartBeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HeartBeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeatResponse_descriptor,
        new java.lang.String[] { "Term", "NodeId", "TimeStampOnLatestUpdate", });
    internal_static_HeartBeatPacket_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_HeartBeatPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeatPacket_descriptor,
        new java.lang.String[] { "UnixTimestamp", "Heartbeat", "HeartBeatResponse", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
