// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/VoteRPC.proto

package pipe.work;

public final class VoteRPC {
  private VoteRPC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestVoteRPCOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestVoteRPC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 term = 1;</code>
     */
    boolean hasTerm();
    /**
     * <code>required int32 term = 1;</code>
     */
    int getTerm();

    /**
     * <code>required string candidateId = 2;</code>
     */
    boolean hasCandidateId();
    /**
     * <code>required string candidateId = 2;</code>
     */
    java.lang.String getCandidateId();
    /**
     * <code>required string candidateId = 2;</code>
     */
    com.google.protobuf.ByteString
        getCandidateIdBytes();

    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    boolean hasTimeStampOnLatestUpdate();
    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    long getTimeStampOnLatestUpdate();
  }
  /**
   * Protobuf type {@code RequestVoteRPC}
   */
  public  static final class RequestVoteRPC extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestVoteRPC)
      RequestVoteRPCOrBuilder {
    // Use RequestVoteRPC.newBuilder() to construct.
    private RequestVoteRPC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestVoteRPC() {
      term_ = 0;
      candidateId_ = "";
      timeStampOnLatestUpdate_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestVoteRPC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              term_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              candidateId_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timeStampOnLatestUpdate_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pipe.work.VoteRPC.internal_static_RequestVoteRPC_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pipe.work.VoteRPC.internal_static_RequestVoteRPC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pipe.work.VoteRPC.RequestVoteRPC.class, pipe.work.VoteRPC.RequestVoteRPC.Builder.class);
    }

    private int bitField0_;
    public static final int TERM_FIELD_NUMBER = 1;
    private int term_;
    /**
     * <code>required int32 term = 1;</code>
     */
    public boolean hasTerm() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 term = 1;</code>
     */
    public int getTerm() {
      return term_;
    }

    public static final int CANDIDATEID_FIELD_NUMBER = 2;
    private volatile java.lang.Object candidateId_;
    /**
     * <code>required string candidateId = 2;</code>
     */
    public boolean hasCandidateId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string candidateId = 2;</code>
     */
    public java.lang.String getCandidateId() {
      java.lang.Object ref = candidateId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          candidateId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string candidateId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCandidateIdBytes() {
      java.lang.Object ref = candidateId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        candidateId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMPONLATESTUPDATE_FIELD_NUMBER = 3;
    private long timeStampOnLatestUpdate_;
    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    public boolean hasTimeStampOnLatestUpdate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    public long getTimeStampOnLatestUpdate() {
      return timeStampOnLatestUpdate_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTerm()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCandidateId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeStampOnLatestUpdate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, candidateId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, timeStampOnLatestUpdate_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, candidateId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timeStampOnLatestUpdate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pipe.work.VoteRPC.RequestVoteRPC)) {
        return super.equals(obj);
      }
      pipe.work.VoteRPC.RequestVoteRPC other = (pipe.work.VoteRPC.RequestVoteRPC) obj;

      boolean result = true;
      result = result && (hasTerm() == other.hasTerm());
      if (hasTerm()) {
        result = result && (getTerm()
            == other.getTerm());
      }
      result = result && (hasCandidateId() == other.hasCandidateId());
      if (hasCandidateId()) {
        result = result && getCandidateId()
            .equals(other.getCandidateId());
      }
      result = result && (hasTimeStampOnLatestUpdate() == other.hasTimeStampOnLatestUpdate());
      if (hasTimeStampOnLatestUpdate()) {
        result = result && (getTimeStampOnLatestUpdate()
            == other.getTimeStampOnLatestUpdate());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTerm()) {
        hash = (37 * hash) + TERM_FIELD_NUMBER;
        hash = (53 * hash) + getTerm();
      }
      if (hasCandidateId()) {
        hash = (37 * hash) + CANDIDATEID_FIELD_NUMBER;
        hash = (53 * hash) + getCandidateId().hashCode();
      }
      if (hasTimeStampOnLatestUpdate()) {
        hash = (37 * hash) + TIMESTAMPONLATESTUPDATE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimeStampOnLatestUpdate());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pipe.work.VoteRPC.RequestVoteRPC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.work.VoteRPC.RequestVoteRPC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.work.VoteRPC.RequestVoteRPC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.work.VoteRPC.RequestVoteRPC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.work.VoteRPC.RequestVoteRPC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.work.VoteRPC.RequestVoteRPC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.work.VoteRPC.RequestVoteRPC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pipe.work.VoteRPC.RequestVoteRPC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.work.VoteRPC.RequestVoteRPC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.work.VoteRPC.RequestVoteRPC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pipe.work.VoteRPC.RequestVoteRPC prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestVoteRPC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestVoteRPC)
        pipe.work.VoteRPC.RequestVoteRPCOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pipe.work.VoteRPC.internal_static_RequestVoteRPC_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pipe.work.VoteRPC.internal_static_RequestVoteRPC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pipe.work.VoteRPC.RequestVoteRPC.class, pipe.work.VoteRPC.RequestVoteRPC.Builder.class);
      }

      // Construct using pipe.work.VoteRPC.RequestVoteRPC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        term_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        candidateId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        timeStampOnLatestUpdate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pipe.work.VoteRPC.internal_static_RequestVoteRPC_descriptor;
      }

      public pipe.work.VoteRPC.RequestVoteRPC getDefaultInstanceForType() {
        return pipe.work.VoteRPC.RequestVoteRPC.getDefaultInstance();
      }

      public pipe.work.VoteRPC.RequestVoteRPC build() {
        pipe.work.VoteRPC.RequestVoteRPC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pipe.work.VoteRPC.RequestVoteRPC buildPartial() {
        pipe.work.VoteRPC.RequestVoteRPC result = new pipe.work.VoteRPC.RequestVoteRPC(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.term_ = term_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.candidateId_ = candidateId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timeStampOnLatestUpdate_ = timeStampOnLatestUpdate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pipe.work.VoteRPC.RequestVoteRPC) {
          return mergeFrom((pipe.work.VoteRPC.RequestVoteRPC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pipe.work.VoteRPC.RequestVoteRPC other) {
        if (other == pipe.work.VoteRPC.RequestVoteRPC.getDefaultInstance()) return this;
        if (other.hasTerm()) {
          setTerm(other.getTerm());
        }
        if (other.hasCandidateId()) {
          bitField0_ |= 0x00000002;
          candidateId_ = other.candidateId_;
          onChanged();
        }
        if (other.hasTimeStampOnLatestUpdate()) {
          setTimeStampOnLatestUpdate(other.getTimeStampOnLatestUpdate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTerm()) {
          return false;
        }
        if (!hasCandidateId()) {
          return false;
        }
        if (!hasTimeStampOnLatestUpdate()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pipe.work.VoteRPC.RequestVoteRPC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pipe.work.VoteRPC.RequestVoteRPC) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int term_ ;
      /**
       * <code>required int32 term = 1;</code>
       */
      public boolean hasTerm() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public int getTerm() {
        return term_;
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public Builder setTerm(int value) {
        bitField0_ |= 0x00000001;
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public Builder clearTerm() {
        bitField0_ = (bitField0_ & ~0x00000001);
        term_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object candidateId_ = "";
      /**
       * <code>required string candidateId = 2;</code>
       */
      public boolean hasCandidateId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string candidateId = 2;</code>
       */
      public java.lang.String getCandidateId() {
        java.lang.Object ref = candidateId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            candidateId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string candidateId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCandidateIdBytes() {
        java.lang.Object ref = candidateId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          candidateId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string candidateId = 2;</code>
       */
      public Builder setCandidateId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        candidateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string candidateId = 2;</code>
       */
      public Builder clearCandidateId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        candidateId_ = getDefaultInstance().getCandidateId();
        onChanged();
        return this;
      }
      /**
       * <code>required string candidateId = 2;</code>
       */
      public Builder setCandidateIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        candidateId_ = value;
        onChanged();
        return this;
      }

      private long timeStampOnLatestUpdate_ ;
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public boolean hasTimeStampOnLatestUpdate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public long getTimeStampOnLatestUpdate() {
        return timeStampOnLatestUpdate_;
      }
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public Builder setTimeStampOnLatestUpdate(long value) {
        bitField0_ |= 0x00000004;
        timeStampOnLatestUpdate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public Builder clearTimeStampOnLatestUpdate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timeStampOnLatestUpdate_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RequestVoteRPC)
    }

    // @@protoc_insertion_point(class_scope:RequestVoteRPC)
    private static final pipe.work.VoteRPC.RequestVoteRPC DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pipe.work.VoteRPC.RequestVoteRPC();
    }

    public static pipe.work.VoteRPC.RequestVoteRPC getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RequestVoteRPC>
        PARSER = new com.google.protobuf.AbstractParser<RequestVoteRPC>() {
      public RequestVoteRPC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestVoteRPC(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestVoteRPC> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestVoteRPC> getParserForType() {
      return PARSER;
    }

    public pipe.work.VoteRPC.RequestVoteRPC getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseVoteRPCOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResponseVoteRPC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 term = 1;</code>
     */
    boolean hasTerm();
    /**
     * <code>required int32 term = 1;</code>
     */
    int getTerm();

    /**
     * <code>required .ResponseVoteRPC.IsVoteGranted isVoteGranted = 2;</code>
     */
    boolean hasIsVoteGranted();
    /**
     * <code>required .ResponseVoteRPC.IsVoteGranted isVoteGranted = 2;</code>
     */
    pipe.work.VoteRPC.ResponseVoteRPC.IsVoteGranted getIsVoteGranted();
  }
  /**
   * Protobuf type {@code ResponseVoteRPC}
   */
  public  static final class ResponseVoteRPC extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResponseVoteRPC)
      ResponseVoteRPCOrBuilder {
    // Use ResponseVoteRPC.newBuilder() to construct.
    private ResponseVoteRPC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseVoteRPC() {
      term_ = 0;
      isVoteGranted_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseVoteRPC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              term_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              pipe.work.VoteRPC.ResponseVoteRPC.IsVoteGranted value = pipe.work.VoteRPC.ResponseVoteRPC.IsVoteGranted.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                isVoteGranted_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pipe.work.VoteRPC.internal_static_ResponseVoteRPC_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pipe.work.VoteRPC.internal_static_ResponseVoteRPC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pipe.work.VoteRPC.ResponseVoteRPC.class, pipe.work.VoteRPC.ResponseVoteRPC.Builder.class);
    }

    /**
     * Protobuf enum {@code ResponseVoteRPC.IsVoteGranted}
     */
    public enum IsVoteGranted
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>YES = 0;</code>
       */
      YES(0),
      /**
       * <code>NO = 1;</code>
       */
      NO(1),
      ;

      /**
       * <code>YES = 0;</code>
       */
      public static final int YES_VALUE = 0;
      /**
       * <code>NO = 1;</code>
       */
      public static final int NO_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static IsVoteGranted valueOf(int value) {
        return forNumber(value);
      }

      public static IsVoteGranted forNumber(int value) {
        switch (value) {
          case 0: return YES;
          case 1: return NO;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<IsVoteGranted>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          IsVoteGranted> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<IsVoteGranted>() {
              public IsVoteGranted findValueByNumber(int number) {
                return IsVoteGranted.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return pipe.work.VoteRPC.ResponseVoteRPC.getDescriptor().getEnumTypes().get(0);
      }

      private static final IsVoteGranted[] VALUES = values();

      public static IsVoteGranted valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private IsVoteGranted(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ResponseVoteRPC.IsVoteGranted)
    }

    private int bitField0_;
    public static final int TERM_FIELD_NUMBER = 1;
    private int term_;
    /**
     * <code>required int32 term = 1;</code>
     */
    public boolean hasTerm() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 term = 1;</code>
     */
    public int getTerm() {
      return term_;
    }

    public static final int ISVOTEGRANTED_FIELD_NUMBER = 2;
    private int isVoteGranted_;
    /**
     * <code>required .ResponseVoteRPC.IsVoteGranted isVoteGranted = 2;</code>
     */
    public boolean hasIsVoteGranted() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .ResponseVoteRPC.IsVoteGranted isVoteGranted = 2;</code>
     */
    public pipe.work.VoteRPC.ResponseVoteRPC.IsVoteGranted getIsVoteGranted() {
      pipe.work.VoteRPC.ResponseVoteRPC.IsVoteGranted result = pipe.work.VoteRPC.ResponseVoteRPC.IsVoteGranted.valueOf(isVoteGranted_);
      return result == null ? pipe.work.VoteRPC.ResponseVoteRPC.IsVoteGranted.YES : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTerm()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsVoteGranted()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, isVoteGranted_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, isVoteGranted_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pipe.work.VoteRPC.ResponseVoteRPC)) {
        return super.equals(obj);
      }
      pipe.work.VoteRPC.ResponseVoteRPC other = (pipe.work.VoteRPC.ResponseVoteRPC) obj;

      boolean result = true;
      result = result && (hasTerm() == other.hasTerm());
      if (hasTerm()) {
        result = result && (getTerm()
            == other.getTerm());
      }
      result = result && (hasIsVoteGranted() == other.hasIsVoteGranted());
      if (hasIsVoteGranted()) {
        result = result && isVoteGranted_ == other.isVoteGranted_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTerm()) {
        hash = (37 * hash) + TERM_FIELD_NUMBER;
        hash = (53 * hash) + getTerm();
      }
      if (hasIsVoteGranted()) {
        hash = (37 * hash) + ISVOTEGRANTED_FIELD_NUMBER;
        hash = (53 * hash) + isVoteGranted_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pipe.work.VoteRPC.ResponseVoteRPC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.work.VoteRPC.ResponseVoteRPC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.work.VoteRPC.ResponseVoteRPC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.work.VoteRPC.ResponseVoteRPC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.work.VoteRPC.ResponseVoteRPC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.work.VoteRPC.ResponseVoteRPC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.work.VoteRPC.ResponseVoteRPC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pipe.work.VoteRPC.ResponseVoteRPC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.work.VoteRPC.ResponseVoteRPC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.work.VoteRPC.ResponseVoteRPC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pipe.work.VoteRPC.ResponseVoteRPC prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResponseVoteRPC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResponseVoteRPC)
        pipe.work.VoteRPC.ResponseVoteRPCOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pipe.work.VoteRPC.internal_static_ResponseVoteRPC_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pipe.work.VoteRPC.internal_static_ResponseVoteRPC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pipe.work.VoteRPC.ResponseVoteRPC.class, pipe.work.VoteRPC.ResponseVoteRPC.Builder.class);
      }

      // Construct using pipe.work.VoteRPC.ResponseVoteRPC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        term_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        isVoteGranted_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pipe.work.VoteRPC.internal_static_ResponseVoteRPC_descriptor;
      }

      public pipe.work.VoteRPC.ResponseVoteRPC getDefaultInstanceForType() {
        return pipe.work.VoteRPC.ResponseVoteRPC.getDefaultInstance();
      }

      public pipe.work.VoteRPC.ResponseVoteRPC build() {
        pipe.work.VoteRPC.ResponseVoteRPC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pipe.work.VoteRPC.ResponseVoteRPC buildPartial() {
        pipe.work.VoteRPC.ResponseVoteRPC result = new pipe.work.VoteRPC.ResponseVoteRPC(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.term_ = term_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isVoteGranted_ = isVoteGranted_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pipe.work.VoteRPC.ResponseVoteRPC) {
          return mergeFrom((pipe.work.VoteRPC.ResponseVoteRPC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pipe.work.VoteRPC.ResponseVoteRPC other) {
        if (other == pipe.work.VoteRPC.ResponseVoteRPC.getDefaultInstance()) return this;
        if (other.hasTerm()) {
          setTerm(other.getTerm());
        }
        if (other.hasIsVoteGranted()) {
          setIsVoteGranted(other.getIsVoteGranted());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTerm()) {
          return false;
        }
        if (!hasIsVoteGranted()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pipe.work.VoteRPC.ResponseVoteRPC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pipe.work.VoteRPC.ResponseVoteRPC) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int term_ ;
      /**
       * <code>required int32 term = 1;</code>
       */
      public boolean hasTerm() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public int getTerm() {
        return term_;
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public Builder setTerm(int value) {
        bitField0_ |= 0x00000001;
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public Builder clearTerm() {
        bitField0_ = (bitField0_ & ~0x00000001);
        term_ = 0;
        onChanged();
        return this;
      }

      private int isVoteGranted_ = 0;
      /**
       * <code>required .ResponseVoteRPC.IsVoteGranted isVoteGranted = 2;</code>
       */
      public boolean hasIsVoteGranted() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .ResponseVoteRPC.IsVoteGranted isVoteGranted = 2;</code>
       */
      public pipe.work.VoteRPC.ResponseVoteRPC.IsVoteGranted getIsVoteGranted() {
        pipe.work.VoteRPC.ResponseVoteRPC.IsVoteGranted result = pipe.work.VoteRPC.ResponseVoteRPC.IsVoteGranted.valueOf(isVoteGranted_);
        return result == null ? pipe.work.VoteRPC.ResponseVoteRPC.IsVoteGranted.YES : result;
      }
      /**
       * <code>required .ResponseVoteRPC.IsVoteGranted isVoteGranted = 2;</code>
       */
      public Builder setIsVoteGranted(pipe.work.VoteRPC.ResponseVoteRPC.IsVoteGranted value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        isVoteGranted_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .ResponseVoteRPC.IsVoteGranted isVoteGranted = 2;</code>
       */
      public Builder clearIsVoteGranted() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isVoteGranted_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ResponseVoteRPC)
    }

    // @@protoc_insertion_point(class_scope:ResponseVoteRPC)
    private static final pipe.work.VoteRPC.ResponseVoteRPC DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pipe.work.VoteRPC.ResponseVoteRPC();
    }

    public static pipe.work.VoteRPC.ResponseVoteRPC getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ResponseVoteRPC>
        PARSER = new com.google.protobuf.AbstractParser<ResponseVoteRPC>() {
      public ResponseVoteRPC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResponseVoteRPC(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseVoteRPC> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseVoteRPC> getParserForType() {
      return PARSER;
    }

    public pipe.work.VoteRPC.ResponseVoteRPC getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VoteRPCPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VoteRPCPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 unixTimestamp = 1;</code>
     */
    boolean hasUnixTimestamp();
    /**
     * <code>required int64 unixTimestamp = 1;</code>
     */
    long getUnixTimestamp();

    /**
     * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
     */
    boolean hasRequestVoteRPC();
    /**
     * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
     */
    pipe.work.VoteRPC.RequestVoteRPC getRequestVoteRPC();
    /**
     * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
     */
    pipe.work.VoteRPC.RequestVoteRPCOrBuilder getRequestVoteRPCOrBuilder();

    /**
     * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
     */
    boolean hasResponseVoteRPC();
    /**
     * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
     */
    pipe.work.VoteRPC.ResponseVoteRPC getResponseVoteRPC();
    /**
     * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
     */
    pipe.work.VoteRPC.ResponseVoteRPCOrBuilder getResponseVoteRPCOrBuilder();

    public pipe.work.VoteRPC.VoteRPCPacket.PayloadCase getPayloadCase();
  }
  /**
   * Protobuf type {@code VoteRPCPacket}
   */
  public  static final class VoteRPCPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:VoteRPCPacket)
      VoteRPCPacketOrBuilder {
    // Use VoteRPCPacket.newBuilder() to construct.
    private VoteRPCPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VoteRPCPacket() {
      unixTimestamp_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VoteRPCPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              unixTimestamp_ = input.readInt64();
              break;
            }
            case 18: {
              pipe.work.VoteRPC.RequestVoteRPC.Builder subBuilder = null;
              if (payloadCase_ == 2) {
                subBuilder = ((pipe.work.VoteRPC.RequestVoteRPC) payload_).toBuilder();
              }
              payload_ =
                  input.readMessage(pipe.work.VoteRPC.RequestVoteRPC.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((pipe.work.VoteRPC.RequestVoteRPC) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 2;
              break;
            }
            case 26: {
              pipe.work.VoteRPC.ResponseVoteRPC.Builder subBuilder = null;
              if (payloadCase_ == 3) {
                subBuilder = ((pipe.work.VoteRPC.ResponseVoteRPC) payload_).toBuilder();
              }
              payload_ =
                  input.readMessage(pipe.work.VoteRPC.ResponseVoteRPC.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((pipe.work.VoteRPC.ResponseVoteRPC) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 3;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pipe.work.VoteRPC.internal_static_VoteRPCPacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pipe.work.VoteRPC.internal_static_VoteRPCPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pipe.work.VoteRPC.VoteRPCPacket.class, pipe.work.VoteRPC.VoteRPCPacket.Builder.class);
    }

    private int bitField0_;
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite {
      REQUESTVOTERPC(2),
      RESPONSEVOTERPC(3),
      PAYLOAD_NOT_SET(0);
      private final int value;
      private PayloadCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PayloadCase valueOf(int value) {
        return forNumber(value);
      }

      public static PayloadCase forNumber(int value) {
        switch (value) {
          case 2: return REQUESTVOTERPC;
          case 3: return RESPONSEVOTERPC;
          case 0: return PAYLOAD_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PayloadCase
    getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public static final int UNIXTIMESTAMP_FIELD_NUMBER = 1;
    private long unixTimestamp_;
    /**
     * <code>required int64 unixTimestamp = 1;</code>
     */
    public boolean hasUnixTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 unixTimestamp = 1;</code>
     */
    public long getUnixTimestamp() {
      return unixTimestamp_;
    }

    public static final int REQUESTVOTERPC_FIELD_NUMBER = 2;
    /**
     * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
     */
    public boolean hasRequestVoteRPC() {
      return payloadCase_ == 2;
    }
    /**
     * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
     */
    public pipe.work.VoteRPC.RequestVoteRPC getRequestVoteRPC() {
      if (payloadCase_ == 2) {
         return (pipe.work.VoteRPC.RequestVoteRPC) payload_;
      }
      return pipe.work.VoteRPC.RequestVoteRPC.getDefaultInstance();
    }
    /**
     * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
     */
    public pipe.work.VoteRPC.RequestVoteRPCOrBuilder getRequestVoteRPCOrBuilder() {
      if (payloadCase_ == 2) {
         return (pipe.work.VoteRPC.RequestVoteRPC) payload_;
      }
      return pipe.work.VoteRPC.RequestVoteRPC.getDefaultInstance();
    }

    public static final int RESPONSEVOTERPC_FIELD_NUMBER = 3;
    /**
     * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
     */
    public boolean hasResponseVoteRPC() {
      return payloadCase_ == 3;
    }
    /**
     * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
     */
    public pipe.work.VoteRPC.ResponseVoteRPC getResponseVoteRPC() {
      if (payloadCase_ == 3) {
         return (pipe.work.VoteRPC.ResponseVoteRPC) payload_;
      }
      return pipe.work.VoteRPC.ResponseVoteRPC.getDefaultInstance();
    }
    /**
     * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
     */
    public pipe.work.VoteRPC.ResponseVoteRPCOrBuilder getResponseVoteRPCOrBuilder() {
      if (payloadCase_ == 3) {
         return (pipe.work.VoteRPC.ResponseVoteRPC) payload_;
      }
      return pipe.work.VoteRPC.ResponseVoteRPC.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUnixTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasRequestVoteRPC()) {
        if (!getRequestVoteRPC().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasResponseVoteRPC()) {
        if (!getResponseVoteRPC().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, unixTimestamp_);
      }
      if (payloadCase_ == 2) {
        output.writeMessage(2, (pipe.work.VoteRPC.RequestVoteRPC) payload_);
      }
      if (payloadCase_ == 3) {
        output.writeMessage(3, (pipe.work.VoteRPC.ResponseVoteRPC) payload_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, unixTimestamp_);
      }
      if (payloadCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (pipe.work.VoteRPC.RequestVoteRPC) payload_);
      }
      if (payloadCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (pipe.work.VoteRPC.ResponseVoteRPC) payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pipe.work.VoteRPC.VoteRPCPacket)) {
        return super.equals(obj);
      }
      pipe.work.VoteRPC.VoteRPCPacket other = (pipe.work.VoteRPC.VoteRPCPacket) obj;

      boolean result = true;
      result = result && (hasUnixTimestamp() == other.hasUnixTimestamp());
      if (hasUnixTimestamp()) {
        result = result && (getUnixTimestamp()
            == other.getUnixTimestamp());
      }
      result = result && getPayloadCase().equals(
          other.getPayloadCase());
      if (!result) return false;
      switch (payloadCase_) {
        case 2:
          result = result && getRequestVoteRPC()
              .equals(other.getRequestVoteRPC());
          break;
        case 3:
          result = result && getResponseVoteRPC()
              .equals(other.getResponseVoteRPC());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUnixTimestamp()) {
        hash = (37 * hash) + UNIXTIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUnixTimestamp());
      }
      switch (payloadCase_) {
        case 2:
          hash = (37 * hash) + REQUESTVOTERPC_FIELD_NUMBER;
          hash = (53 * hash) + getRequestVoteRPC().hashCode();
          break;
        case 3:
          hash = (37 * hash) + RESPONSEVOTERPC_FIELD_NUMBER;
          hash = (53 * hash) + getResponseVoteRPC().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pipe.work.VoteRPC.VoteRPCPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.work.VoteRPC.VoteRPCPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.work.VoteRPC.VoteRPCPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.work.VoteRPC.VoteRPCPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.work.VoteRPC.VoteRPCPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.work.VoteRPC.VoteRPCPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.work.VoteRPC.VoteRPCPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pipe.work.VoteRPC.VoteRPCPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.work.VoteRPC.VoteRPCPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.work.VoteRPC.VoteRPCPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pipe.work.VoteRPC.VoteRPCPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VoteRPCPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VoteRPCPacket)
        pipe.work.VoteRPC.VoteRPCPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pipe.work.VoteRPC.internal_static_VoteRPCPacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pipe.work.VoteRPC.internal_static_VoteRPCPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pipe.work.VoteRPC.VoteRPCPacket.class, pipe.work.VoteRPC.VoteRPCPacket.Builder.class);
      }

      // Construct using pipe.work.VoteRPC.VoteRPCPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        unixTimestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        payloadCase_ = 0;
        payload_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pipe.work.VoteRPC.internal_static_VoteRPCPacket_descriptor;
      }

      public pipe.work.VoteRPC.VoteRPCPacket getDefaultInstanceForType() {
        return pipe.work.VoteRPC.VoteRPCPacket.getDefaultInstance();
      }

      public pipe.work.VoteRPC.VoteRPCPacket build() {
        pipe.work.VoteRPC.VoteRPCPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pipe.work.VoteRPC.VoteRPCPacket buildPartial() {
        pipe.work.VoteRPC.VoteRPCPacket result = new pipe.work.VoteRPC.VoteRPCPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.unixTimestamp_ = unixTimestamp_;
        if (payloadCase_ == 2) {
          if (requestVoteRPCBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = requestVoteRPCBuilder_.build();
          }
        }
        if (payloadCase_ == 3) {
          if (responseVoteRPCBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = responseVoteRPCBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.payloadCase_ = payloadCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pipe.work.VoteRPC.VoteRPCPacket) {
          return mergeFrom((pipe.work.VoteRPC.VoteRPCPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pipe.work.VoteRPC.VoteRPCPacket other) {
        if (other == pipe.work.VoteRPC.VoteRPCPacket.getDefaultInstance()) return this;
        if (other.hasUnixTimestamp()) {
          setUnixTimestamp(other.getUnixTimestamp());
        }
        switch (other.getPayloadCase()) {
          case REQUESTVOTERPC: {
            mergeRequestVoteRPC(other.getRequestVoteRPC());
            break;
          }
          case RESPONSEVOTERPC: {
            mergeResponseVoteRPC(other.getResponseVoteRPC());
            break;
          }
          case PAYLOAD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUnixTimestamp()) {
          return false;
        }
        if (hasRequestVoteRPC()) {
          if (!getRequestVoteRPC().isInitialized()) {
            return false;
          }
        }
        if (hasResponseVoteRPC()) {
          if (!getResponseVoteRPC().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pipe.work.VoteRPC.VoteRPCPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pipe.work.VoteRPC.VoteRPCPacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int payloadCase_ = 0;
      private java.lang.Object payload_;
      public PayloadCase
          getPayloadCase() {
        return PayloadCase.forNumber(
            payloadCase_);
      }

      public Builder clearPayload() {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private long unixTimestamp_ ;
      /**
       * <code>required int64 unixTimestamp = 1;</code>
       */
      public boolean hasUnixTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 unixTimestamp = 1;</code>
       */
      public long getUnixTimestamp() {
        return unixTimestamp_;
      }
      /**
       * <code>required int64 unixTimestamp = 1;</code>
       */
      public Builder setUnixTimestamp(long value) {
        bitField0_ |= 0x00000001;
        unixTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 unixTimestamp = 1;</code>
       */
      public Builder clearUnixTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        unixTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.work.VoteRPC.RequestVoteRPC, pipe.work.VoteRPC.RequestVoteRPC.Builder, pipe.work.VoteRPC.RequestVoteRPCOrBuilder> requestVoteRPCBuilder_;
      /**
       * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
       */
      public boolean hasRequestVoteRPC() {
        return payloadCase_ == 2;
      }
      /**
       * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
       */
      public pipe.work.VoteRPC.RequestVoteRPC getRequestVoteRPC() {
        if (requestVoteRPCBuilder_ == null) {
          if (payloadCase_ == 2) {
            return (pipe.work.VoteRPC.RequestVoteRPC) payload_;
          }
          return pipe.work.VoteRPC.RequestVoteRPC.getDefaultInstance();
        } else {
          if (payloadCase_ == 2) {
            return requestVoteRPCBuilder_.getMessage();
          }
          return pipe.work.VoteRPC.RequestVoteRPC.getDefaultInstance();
        }
      }
      /**
       * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
       */
      public Builder setRequestVoteRPC(pipe.work.VoteRPC.RequestVoteRPC value) {
        if (requestVoteRPCBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          requestVoteRPCBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
       */
      public Builder setRequestVoteRPC(
          pipe.work.VoteRPC.RequestVoteRPC.Builder builderForValue) {
        if (requestVoteRPCBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          requestVoteRPCBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
       */
      public Builder mergeRequestVoteRPC(pipe.work.VoteRPC.RequestVoteRPC value) {
        if (requestVoteRPCBuilder_ == null) {
          if (payloadCase_ == 2 &&
              payload_ != pipe.work.VoteRPC.RequestVoteRPC.getDefaultInstance()) {
            payload_ = pipe.work.VoteRPC.RequestVoteRPC.newBuilder((pipe.work.VoteRPC.RequestVoteRPC) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 2) {
            requestVoteRPCBuilder_.mergeFrom(value);
          }
          requestVoteRPCBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
       */
      public Builder clearRequestVoteRPC() {
        if (requestVoteRPCBuilder_ == null) {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
          }
          requestVoteRPCBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
       */
      public pipe.work.VoteRPC.RequestVoteRPC.Builder getRequestVoteRPCBuilder() {
        return getRequestVoteRPCFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
       */
      public pipe.work.VoteRPC.RequestVoteRPCOrBuilder getRequestVoteRPCOrBuilder() {
        if ((payloadCase_ == 2) && (requestVoteRPCBuilder_ != null)) {
          return requestVoteRPCBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 2) {
            return (pipe.work.VoteRPC.RequestVoteRPC) payload_;
          }
          return pipe.work.VoteRPC.RequestVoteRPC.getDefaultInstance();
        }
      }
      /**
       * <code>optional .RequestVoteRPC requestVoteRPC = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.work.VoteRPC.RequestVoteRPC, pipe.work.VoteRPC.RequestVoteRPC.Builder, pipe.work.VoteRPC.RequestVoteRPCOrBuilder> 
          getRequestVoteRPCFieldBuilder() {
        if (requestVoteRPCBuilder_ == null) {
          if (!(payloadCase_ == 2)) {
            payload_ = pipe.work.VoteRPC.RequestVoteRPC.getDefaultInstance();
          }
          requestVoteRPCBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pipe.work.VoteRPC.RequestVoteRPC, pipe.work.VoteRPC.RequestVoteRPC.Builder, pipe.work.VoteRPC.RequestVoteRPCOrBuilder>(
                  (pipe.work.VoteRPC.RequestVoteRPC) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 2;
        onChanged();;
        return requestVoteRPCBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.work.VoteRPC.ResponseVoteRPC, pipe.work.VoteRPC.ResponseVoteRPC.Builder, pipe.work.VoteRPC.ResponseVoteRPCOrBuilder> responseVoteRPCBuilder_;
      /**
       * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
       */
      public boolean hasResponseVoteRPC() {
        return payloadCase_ == 3;
      }
      /**
       * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
       */
      public pipe.work.VoteRPC.ResponseVoteRPC getResponseVoteRPC() {
        if (responseVoteRPCBuilder_ == null) {
          if (payloadCase_ == 3) {
            return (pipe.work.VoteRPC.ResponseVoteRPC) payload_;
          }
          return pipe.work.VoteRPC.ResponseVoteRPC.getDefaultInstance();
        } else {
          if (payloadCase_ == 3) {
            return responseVoteRPCBuilder_.getMessage();
          }
          return pipe.work.VoteRPC.ResponseVoteRPC.getDefaultInstance();
        }
      }
      /**
       * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
       */
      public Builder setResponseVoteRPC(pipe.work.VoteRPC.ResponseVoteRPC value) {
        if (responseVoteRPCBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          responseVoteRPCBuilder_.setMessage(value);
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
       */
      public Builder setResponseVoteRPC(
          pipe.work.VoteRPC.ResponseVoteRPC.Builder builderForValue) {
        if (responseVoteRPCBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          responseVoteRPCBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
       */
      public Builder mergeResponseVoteRPC(pipe.work.VoteRPC.ResponseVoteRPC value) {
        if (responseVoteRPCBuilder_ == null) {
          if (payloadCase_ == 3 &&
              payload_ != pipe.work.VoteRPC.ResponseVoteRPC.getDefaultInstance()) {
            payload_ = pipe.work.VoteRPC.ResponseVoteRPC.newBuilder((pipe.work.VoteRPC.ResponseVoteRPC) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 3) {
            responseVoteRPCBuilder_.mergeFrom(value);
          }
          responseVoteRPCBuilder_.setMessage(value);
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
       */
      public Builder clearResponseVoteRPC() {
        if (responseVoteRPCBuilder_ == null) {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
          }
          responseVoteRPCBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
       */
      public pipe.work.VoteRPC.ResponseVoteRPC.Builder getResponseVoteRPCBuilder() {
        return getResponseVoteRPCFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
       */
      public pipe.work.VoteRPC.ResponseVoteRPCOrBuilder getResponseVoteRPCOrBuilder() {
        if ((payloadCase_ == 3) && (responseVoteRPCBuilder_ != null)) {
          return responseVoteRPCBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 3) {
            return (pipe.work.VoteRPC.ResponseVoteRPC) payload_;
          }
          return pipe.work.VoteRPC.ResponseVoteRPC.getDefaultInstance();
        }
      }
      /**
       * <code>optional .ResponseVoteRPC responseVoteRPC = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.work.VoteRPC.ResponseVoteRPC, pipe.work.VoteRPC.ResponseVoteRPC.Builder, pipe.work.VoteRPC.ResponseVoteRPCOrBuilder> 
          getResponseVoteRPCFieldBuilder() {
        if (responseVoteRPCBuilder_ == null) {
          if (!(payloadCase_ == 3)) {
            payload_ = pipe.work.VoteRPC.ResponseVoteRPC.getDefaultInstance();
          }
          responseVoteRPCBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pipe.work.VoteRPC.ResponseVoteRPC, pipe.work.VoteRPC.ResponseVoteRPC.Builder, pipe.work.VoteRPC.ResponseVoteRPCOrBuilder>(
                  (pipe.work.VoteRPC.ResponseVoteRPC) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 3;
        onChanged();;
        return responseVoteRPCBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:VoteRPCPacket)
    }

    // @@protoc_insertion_point(class_scope:VoteRPCPacket)
    private static final pipe.work.VoteRPC.VoteRPCPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pipe.work.VoteRPC.VoteRPCPacket();
    }

    public static pipe.work.VoteRPC.VoteRPCPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<VoteRPCPacket>
        PARSER = new com.google.protobuf.AbstractParser<VoteRPCPacket>() {
      public VoteRPCPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new VoteRPCPacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VoteRPCPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VoteRPCPacket> getParserForType() {
      return PARSER;
    }

    public pipe.work.VoteRPC.VoteRPCPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestVoteRPC_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestVoteRPC_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseVoteRPC_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseVoteRPC_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VoteRPCPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VoteRPCPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027resources/VoteRPC.proto\"T\n\016RequestVote" +
      "RPC\022\014\n\004term\030\001 \002(\005\022\023\n\013candidateId\030\002 \002(\t\022\037" +
      "\n\027timeStampOnLatestUpdate\030\003 \002(\003\"x\n\017Respo" +
      "nseVoteRPC\022\014\n\004term\030\001 \002(\005\0225\n\risVoteGrante" +
      "d\030\002 \002(\0162\036.ResponseVoteRPC.IsVoteGranted\"" +
      " \n\rIsVoteGranted\022\007\n\003YES\020\000\022\006\n\002NO\020\001\"\211\001\n\rVo" +
      "teRPCPacket\022\025\n\runixTimestamp\030\001 \002(\003\022)\n\016re" +
      "questVoteRPC\030\002 \001(\0132\017.RequestVoteRPCH\000\022+\n" +
      "\017responseVoteRPC\030\003 \001(\0132\020.ResponseVoteRPC" +
      "H\000B\t\n\007payloadB\013\n\tpipe.work"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RequestVoteRPC_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestVoteRPC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestVoteRPC_descriptor,
        new java.lang.String[] { "Term", "CandidateId", "TimeStampOnLatestUpdate", });
    internal_static_ResponseVoteRPC_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResponseVoteRPC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseVoteRPC_descriptor,
        new java.lang.String[] { "Term", "IsVoteGranted", });
    internal_static_VoteRPCPacket_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_VoteRPCPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VoteRPCPacket_descriptor,
        new java.lang.String[] { "UnixTimestamp", "RequestVoteRPC", "ResponseVoteRPC", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
