// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/work.proto

package pipe.work;

public final class Work {
  private Work() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WorkMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WorkMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 unixTimeStamp = 1;</code>
     */
    boolean hasUnixTimeStamp();
    /**
     * <code>required int64 unixTimeStamp = 1;</code>
     */
    long getUnixTimeStamp();

    /**
     * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
     */
    boolean hasAppendEntriesPacket();
    /**
     * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
     */
    pipe.work.AppendEntriesRPC.AppendEntriesPacket getAppendEntriesPacket();
    /**
     * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
     */
    pipe.work.AppendEntriesRPC.AppendEntriesPacketOrBuilder getAppendEntriesPacketOrBuilder();

    /**
     * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
     */
    boolean hasHeartBeatPacket();
    /**
     * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
     */
    pipe.work.HeartBeatRPC.HeartBeatPacket getHeartBeatPacket();
    /**
     * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
     */
    pipe.work.HeartBeatRPC.HeartBeatPacketOrBuilder getHeartBeatPacketOrBuilder();

    /**
     * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
     */
    boolean hasVoteRPCPacket();
    /**
     * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
     */
    pipe.work.VoteRPC.VoteRPCPacket getVoteRPCPacket();
    /**
     * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
     */
    pipe.work.VoteRPC.VoteRPCPacketOrBuilder getVoteRPCPacketOrBuilder();

    /**
     * <code>optional .PingMessage trivialPing = 5;</code>
     */
    boolean hasTrivialPing();
    /**
     * <code>optional .PingMessage trivialPing = 5;</code>
     */
    pipe.work.Ping.PingMessage getTrivialPing();
    /**
     * <code>optional .PingMessage trivialPing = 5;</code>
     */
    pipe.work.Ping.PingMessageOrBuilder getTrivialPingOrBuilder();

    public pipe.work.Work.WorkMessage.PayloadCase getPayloadCase();
  }
  /**
   * <pre>
   *-------------------------------------------------------------------------------------
   * </pre>
   *
   * Protobuf type {@code WorkMessage}
   */
  public  static final class WorkMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WorkMessage)
      WorkMessageOrBuilder {
    // Use WorkMessage.newBuilder() to construct.
    private WorkMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WorkMessage() {
      unixTimeStamp_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WorkMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              unixTimeStamp_ = input.readInt64();
              break;
            }
            case 18: {
              pipe.work.AppendEntriesRPC.AppendEntriesPacket.Builder subBuilder = null;
              if (payloadCase_ == 2) {
                subBuilder = ((pipe.work.AppendEntriesRPC.AppendEntriesPacket) payload_).toBuilder();
              }
              payload_ =
                  input.readMessage(pipe.work.AppendEntriesRPC.AppendEntriesPacket.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((pipe.work.AppendEntriesRPC.AppendEntriesPacket) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 2;
              break;
            }
            case 26: {
              pipe.work.HeartBeatRPC.HeartBeatPacket.Builder subBuilder = null;
              if (payloadCase_ == 3) {
                subBuilder = ((pipe.work.HeartBeatRPC.HeartBeatPacket) payload_).toBuilder();
              }
              payload_ =
                  input.readMessage(pipe.work.HeartBeatRPC.HeartBeatPacket.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((pipe.work.HeartBeatRPC.HeartBeatPacket) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 3;
              break;
            }
            case 34: {
              pipe.work.VoteRPC.VoteRPCPacket.Builder subBuilder = null;
              if (payloadCase_ == 4) {
                subBuilder = ((pipe.work.VoteRPC.VoteRPCPacket) payload_).toBuilder();
              }
              payload_ =
                  input.readMessage(pipe.work.VoteRPC.VoteRPCPacket.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((pipe.work.VoteRPC.VoteRPCPacket) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 4;
              break;
            }
            case 42: {
              pipe.work.Ping.PingMessage.Builder subBuilder = null;
              if (payloadCase_ == 5) {
                subBuilder = ((pipe.work.Ping.PingMessage) payload_).toBuilder();
              }
              payload_ =
                  input.readMessage(pipe.work.Ping.PingMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((pipe.work.Ping.PingMessage) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 5;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pipe.work.Work.internal_static_WorkMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pipe.work.Work.internal_static_WorkMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pipe.work.Work.WorkMessage.class, pipe.work.Work.WorkMessage.Builder.class);
    }

    private int bitField0_;
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite {
      APPENDENTRIESPACKET(2),
      HEARTBEATPACKET(3),
      VOTERPCPACKET(4),
      TRIVIALPING(5),
      PAYLOAD_NOT_SET(0);
      private final int value;
      private PayloadCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PayloadCase valueOf(int value) {
        return forNumber(value);
      }

      public static PayloadCase forNumber(int value) {
        switch (value) {
          case 2: return APPENDENTRIESPACKET;
          case 3: return HEARTBEATPACKET;
          case 4: return VOTERPCPACKET;
          case 5: return TRIVIALPING;
          case 0: return PAYLOAD_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PayloadCase
    getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public static final int UNIXTIMESTAMP_FIELD_NUMBER = 1;
    private long unixTimeStamp_;
    /**
     * <code>required int64 unixTimeStamp = 1;</code>
     */
    public boolean hasUnixTimeStamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 unixTimeStamp = 1;</code>
     */
    public long getUnixTimeStamp() {
      return unixTimeStamp_;
    }

    public static final int APPENDENTRIESPACKET_FIELD_NUMBER = 2;
    /**
     * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
     */
    public boolean hasAppendEntriesPacket() {
      return payloadCase_ == 2;
    }
    /**
     * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
     */
    public pipe.work.AppendEntriesRPC.AppendEntriesPacket getAppendEntriesPacket() {
      if (payloadCase_ == 2) {
         return (pipe.work.AppendEntriesRPC.AppendEntriesPacket) payload_;
      }
      return pipe.work.AppendEntriesRPC.AppendEntriesPacket.getDefaultInstance();
    }
    /**
     * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
     */
    public pipe.work.AppendEntriesRPC.AppendEntriesPacketOrBuilder getAppendEntriesPacketOrBuilder() {
      if (payloadCase_ == 2) {
         return (pipe.work.AppendEntriesRPC.AppendEntriesPacket) payload_;
      }
      return pipe.work.AppendEntriesRPC.AppendEntriesPacket.getDefaultInstance();
    }

    public static final int HEARTBEATPACKET_FIELD_NUMBER = 3;
    /**
     * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
     */
    public boolean hasHeartBeatPacket() {
      return payloadCase_ == 3;
    }
    /**
     * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
     */
    public pipe.work.HeartBeatRPC.HeartBeatPacket getHeartBeatPacket() {
      if (payloadCase_ == 3) {
         return (pipe.work.HeartBeatRPC.HeartBeatPacket) payload_;
      }
      return pipe.work.HeartBeatRPC.HeartBeatPacket.getDefaultInstance();
    }
    /**
     * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
     */
    public pipe.work.HeartBeatRPC.HeartBeatPacketOrBuilder getHeartBeatPacketOrBuilder() {
      if (payloadCase_ == 3) {
         return (pipe.work.HeartBeatRPC.HeartBeatPacket) payload_;
      }
      return pipe.work.HeartBeatRPC.HeartBeatPacket.getDefaultInstance();
    }

    public static final int VOTERPCPACKET_FIELD_NUMBER = 4;
    /**
     * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
     */
    public boolean hasVoteRPCPacket() {
      return payloadCase_ == 4;
    }
    /**
     * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
     */
    public pipe.work.VoteRPC.VoteRPCPacket getVoteRPCPacket() {
      if (payloadCase_ == 4) {
         return (pipe.work.VoteRPC.VoteRPCPacket) payload_;
      }
      return pipe.work.VoteRPC.VoteRPCPacket.getDefaultInstance();
    }
    /**
     * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
     */
    public pipe.work.VoteRPC.VoteRPCPacketOrBuilder getVoteRPCPacketOrBuilder() {
      if (payloadCase_ == 4) {
         return (pipe.work.VoteRPC.VoteRPCPacket) payload_;
      }
      return pipe.work.VoteRPC.VoteRPCPacket.getDefaultInstance();
    }

    public static final int TRIVIALPING_FIELD_NUMBER = 5;
    /**
     * <code>optional .PingMessage trivialPing = 5;</code>
     */
    public boolean hasTrivialPing() {
      return payloadCase_ == 5;
    }
    /**
     * <code>optional .PingMessage trivialPing = 5;</code>
     */
    public pipe.work.Ping.PingMessage getTrivialPing() {
      if (payloadCase_ == 5) {
         return (pipe.work.Ping.PingMessage) payload_;
      }
      return pipe.work.Ping.PingMessage.getDefaultInstance();
    }
    /**
     * <code>optional .PingMessage trivialPing = 5;</code>
     */
    public pipe.work.Ping.PingMessageOrBuilder getTrivialPingOrBuilder() {
      if (payloadCase_ == 5) {
         return (pipe.work.Ping.PingMessage) payload_;
      }
      return pipe.work.Ping.PingMessage.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUnixTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasAppendEntriesPacket()) {
        if (!getAppendEntriesPacket().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasHeartBeatPacket()) {
        if (!getHeartBeatPacket().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasVoteRPCPacket()) {
        if (!getVoteRPCPacket().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasTrivialPing()) {
        if (!getTrivialPing().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, unixTimeStamp_);
      }
      if (payloadCase_ == 2) {
        output.writeMessage(2, (pipe.work.AppendEntriesRPC.AppendEntriesPacket) payload_);
      }
      if (payloadCase_ == 3) {
        output.writeMessage(3, (pipe.work.HeartBeatRPC.HeartBeatPacket) payload_);
      }
      if (payloadCase_ == 4) {
        output.writeMessage(4, (pipe.work.VoteRPC.VoteRPCPacket) payload_);
      }
      if (payloadCase_ == 5) {
        output.writeMessage(5, (pipe.work.Ping.PingMessage) payload_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, unixTimeStamp_);
      }
      if (payloadCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (pipe.work.AppendEntriesRPC.AppendEntriesPacket) payload_);
      }
      if (payloadCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (pipe.work.HeartBeatRPC.HeartBeatPacket) payload_);
      }
      if (payloadCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (pipe.work.VoteRPC.VoteRPCPacket) payload_);
      }
      if (payloadCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (pipe.work.Ping.PingMessage) payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pipe.work.Work.WorkMessage)) {
        return super.equals(obj);
      }
      pipe.work.Work.WorkMessage other = (pipe.work.Work.WorkMessage) obj;

      boolean result = true;
      result = result && (hasUnixTimeStamp() == other.hasUnixTimeStamp());
      if (hasUnixTimeStamp()) {
        result = result && (getUnixTimeStamp()
            == other.getUnixTimeStamp());
      }
      result = result && getPayloadCase().equals(
          other.getPayloadCase());
      if (!result) return false;
      switch (payloadCase_) {
        case 2:
          result = result && getAppendEntriesPacket()
              .equals(other.getAppendEntriesPacket());
          break;
        case 3:
          result = result && getHeartBeatPacket()
              .equals(other.getHeartBeatPacket());
          break;
        case 4:
          result = result && getVoteRPCPacket()
              .equals(other.getVoteRPCPacket());
          break;
        case 5:
          result = result && getTrivialPing()
              .equals(other.getTrivialPing());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUnixTimeStamp()) {
        hash = (37 * hash) + UNIXTIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUnixTimeStamp());
      }
      switch (payloadCase_) {
        case 2:
          hash = (37 * hash) + APPENDENTRIESPACKET_FIELD_NUMBER;
          hash = (53 * hash) + getAppendEntriesPacket().hashCode();
          break;
        case 3:
          hash = (37 * hash) + HEARTBEATPACKET_FIELD_NUMBER;
          hash = (53 * hash) + getHeartBeatPacket().hashCode();
          break;
        case 4:
          hash = (37 * hash) + VOTERPCPACKET_FIELD_NUMBER;
          hash = (53 * hash) + getVoteRPCPacket().hashCode();
          break;
        case 5:
          hash = (37 * hash) + TRIVIALPING_FIELD_NUMBER;
          hash = (53 * hash) + getTrivialPing().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pipe.work.Work.WorkMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.work.Work.WorkMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.work.Work.WorkMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.work.Work.WorkMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.work.Work.WorkMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.work.Work.WorkMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.work.Work.WorkMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pipe.work.Work.WorkMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.work.Work.WorkMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.work.Work.WorkMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pipe.work.Work.WorkMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *-------------------------------------------------------------------------------------
     * </pre>
     *
     * Protobuf type {@code WorkMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WorkMessage)
        pipe.work.Work.WorkMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pipe.work.Work.internal_static_WorkMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pipe.work.Work.internal_static_WorkMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pipe.work.Work.WorkMessage.class, pipe.work.Work.WorkMessage.Builder.class);
      }

      // Construct using pipe.work.Work.WorkMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        unixTimeStamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        payloadCase_ = 0;
        payload_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pipe.work.Work.internal_static_WorkMessage_descriptor;
      }

      public pipe.work.Work.WorkMessage getDefaultInstanceForType() {
        return pipe.work.Work.WorkMessage.getDefaultInstance();
      }

      public pipe.work.Work.WorkMessage build() {
        pipe.work.Work.WorkMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pipe.work.Work.WorkMessage buildPartial() {
        pipe.work.Work.WorkMessage result = new pipe.work.Work.WorkMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.unixTimeStamp_ = unixTimeStamp_;
        if (payloadCase_ == 2) {
          if (appendEntriesPacketBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = appendEntriesPacketBuilder_.build();
          }
        }
        if (payloadCase_ == 3) {
          if (heartBeatPacketBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = heartBeatPacketBuilder_.build();
          }
        }
        if (payloadCase_ == 4) {
          if (voteRPCPacketBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = voteRPCPacketBuilder_.build();
          }
        }
        if (payloadCase_ == 5) {
          if (trivialPingBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = trivialPingBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.payloadCase_ = payloadCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pipe.work.Work.WorkMessage) {
          return mergeFrom((pipe.work.Work.WorkMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pipe.work.Work.WorkMessage other) {
        if (other == pipe.work.Work.WorkMessage.getDefaultInstance()) return this;
        if (other.hasUnixTimeStamp()) {
          setUnixTimeStamp(other.getUnixTimeStamp());
        }
        switch (other.getPayloadCase()) {
          case APPENDENTRIESPACKET: {
            mergeAppendEntriesPacket(other.getAppendEntriesPacket());
            break;
          }
          case HEARTBEATPACKET: {
            mergeHeartBeatPacket(other.getHeartBeatPacket());
            break;
          }
          case VOTERPCPACKET: {
            mergeVoteRPCPacket(other.getVoteRPCPacket());
            break;
          }
          case TRIVIALPING: {
            mergeTrivialPing(other.getTrivialPing());
            break;
          }
          case PAYLOAD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUnixTimeStamp()) {
          return false;
        }
        if (hasAppendEntriesPacket()) {
          if (!getAppendEntriesPacket().isInitialized()) {
            return false;
          }
        }
        if (hasHeartBeatPacket()) {
          if (!getHeartBeatPacket().isInitialized()) {
            return false;
          }
        }
        if (hasVoteRPCPacket()) {
          if (!getVoteRPCPacket().isInitialized()) {
            return false;
          }
        }
        if (hasTrivialPing()) {
          if (!getTrivialPing().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pipe.work.Work.WorkMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pipe.work.Work.WorkMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int payloadCase_ = 0;
      private java.lang.Object payload_;
      public PayloadCase
          getPayloadCase() {
        return PayloadCase.forNumber(
            payloadCase_);
      }

      public Builder clearPayload() {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private long unixTimeStamp_ ;
      /**
       * <code>required int64 unixTimeStamp = 1;</code>
       */
      public boolean hasUnixTimeStamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 unixTimeStamp = 1;</code>
       */
      public long getUnixTimeStamp() {
        return unixTimeStamp_;
      }
      /**
       * <code>required int64 unixTimeStamp = 1;</code>
       */
      public Builder setUnixTimeStamp(long value) {
        bitField0_ |= 0x00000001;
        unixTimeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 unixTimeStamp = 1;</code>
       */
      public Builder clearUnixTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        unixTimeStamp_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.work.AppendEntriesRPC.AppendEntriesPacket, pipe.work.AppendEntriesRPC.AppendEntriesPacket.Builder, pipe.work.AppendEntriesRPC.AppendEntriesPacketOrBuilder> appendEntriesPacketBuilder_;
      /**
       * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
       */
      public boolean hasAppendEntriesPacket() {
        return payloadCase_ == 2;
      }
      /**
       * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
       */
      public pipe.work.AppendEntriesRPC.AppendEntriesPacket getAppendEntriesPacket() {
        if (appendEntriesPacketBuilder_ == null) {
          if (payloadCase_ == 2) {
            return (pipe.work.AppendEntriesRPC.AppendEntriesPacket) payload_;
          }
          return pipe.work.AppendEntriesRPC.AppendEntriesPacket.getDefaultInstance();
        } else {
          if (payloadCase_ == 2) {
            return appendEntriesPacketBuilder_.getMessage();
          }
          return pipe.work.AppendEntriesRPC.AppendEntriesPacket.getDefaultInstance();
        }
      }
      /**
       * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
       */
      public Builder setAppendEntriesPacket(pipe.work.AppendEntriesRPC.AppendEntriesPacket value) {
        if (appendEntriesPacketBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          appendEntriesPacketBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
       */
      public Builder setAppendEntriesPacket(
          pipe.work.AppendEntriesRPC.AppendEntriesPacket.Builder builderForValue) {
        if (appendEntriesPacketBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          appendEntriesPacketBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
       */
      public Builder mergeAppendEntriesPacket(pipe.work.AppendEntriesRPC.AppendEntriesPacket value) {
        if (appendEntriesPacketBuilder_ == null) {
          if (payloadCase_ == 2 &&
              payload_ != pipe.work.AppendEntriesRPC.AppendEntriesPacket.getDefaultInstance()) {
            payload_ = pipe.work.AppendEntriesRPC.AppendEntriesPacket.newBuilder((pipe.work.AppendEntriesRPC.AppendEntriesPacket) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 2) {
            appendEntriesPacketBuilder_.mergeFrom(value);
          }
          appendEntriesPacketBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
       */
      public Builder clearAppendEntriesPacket() {
        if (appendEntriesPacketBuilder_ == null) {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
          }
          appendEntriesPacketBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
       */
      public pipe.work.AppendEntriesRPC.AppendEntriesPacket.Builder getAppendEntriesPacketBuilder() {
        return getAppendEntriesPacketFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
       */
      public pipe.work.AppendEntriesRPC.AppendEntriesPacketOrBuilder getAppendEntriesPacketOrBuilder() {
        if ((payloadCase_ == 2) && (appendEntriesPacketBuilder_ != null)) {
          return appendEntriesPacketBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 2) {
            return (pipe.work.AppendEntriesRPC.AppendEntriesPacket) payload_;
          }
          return pipe.work.AppendEntriesRPC.AppendEntriesPacket.getDefaultInstance();
        }
      }
      /**
       * <code>optional .AppendEntriesPacket appendEntriesPacket = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.work.AppendEntriesRPC.AppendEntriesPacket, pipe.work.AppendEntriesRPC.AppendEntriesPacket.Builder, pipe.work.AppendEntriesRPC.AppendEntriesPacketOrBuilder> 
          getAppendEntriesPacketFieldBuilder() {
        if (appendEntriesPacketBuilder_ == null) {
          if (!(payloadCase_ == 2)) {
            payload_ = pipe.work.AppendEntriesRPC.AppendEntriesPacket.getDefaultInstance();
          }
          appendEntriesPacketBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pipe.work.AppendEntriesRPC.AppendEntriesPacket, pipe.work.AppendEntriesRPC.AppendEntriesPacket.Builder, pipe.work.AppendEntriesRPC.AppendEntriesPacketOrBuilder>(
                  (pipe.work.AppendEntriesRPC.AppendEntriesPacket) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 2;
        onChanged();;
        return appendEntriesPacketBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.work.HeartBeatRPC.HeartBeatPacket, pipe.work.HeartBeatRPC.HeartBeatPacket.Builder, pipe.work.HeartBeatRPC.HeartBeatPacketOrBuilder> heartBeatPacketBuilder_;
      /**
       * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
       */
      public boolean hasHeartBeatPacket() {
        return payloadCase_ == 3;
      }
      /**
       * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
       */
      public pipe.work.HeartBeatRPC.HeartBeatPacket getHeartBeatPacket() {
        if (heartBeatPacketBuilder_ == null) {
          if (payloadCase_ == 3) {
            return (pipe.work.HeartBeatRPC.HeartBeatPacket) payload_;
          }
          return pipe.work.HeartBeatRPC.HeartBeatPacket.getDefaultInstance();
        } else {
          if (payloadCase_ == 3) {
            return heartBeatPacketBuilder_.getMessage();
          }
          return pipe.work.HeartBeatRPC.HeartBeatPacket.getDefaultInstance();
        }
      }
      /**
       * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
       */
      public Builder setHeartBeatPacket(pipe.work.HeartBeatRPC.HeartBeatPacket value) {
        if (heartBeatPacketBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          heartBeatPacketBuilder_.setMessage(value);
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
       */
      public Builder setHeartBeatPacket(
          pipe.work.HeartBeatRPC.HeartBeatPacket.Builder builderForValue) {
        if (heartBeatPacketBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          heartBeatPacketBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
       */
      public Builder mergeHeartBeatPacket(pipe.work.HeartBeatRPC.HeartBeatPacket value) {
        if (heartBeatPacketBuilder_ == null) {
          if (payloadCase_ == 3 &&
              payload_ != pipe.work.HeartBeatRPC.HeartBeatPacket.getDefaultInstance()) {
            payload_ = pipe.work.HeartBeatRPC.HeartBeatPacket.newBuilder((pipe.work.HeartBeatRPC.HeartBeatPacket) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 3) {
            heartBeatPacketBuilder_.mergeFrom(value);
          }
          heartBeatPacketBuilder_.setMessage(value);
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
       */
      public Builder clearHeartBeatPacket() {
        if (heartBeatPacketBuilder_ == null) {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
          }
          heartBeatPacketBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
       */
      public pipe.work.HeartBeatRPC.HeartBeatPacket.Builder getHeartBeatPacketBuilder() {
        return getHeartBeatPacketFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
       */
      public pipe.work.HeartBeatRPC.HeartBeatPacketOrBuilder getHeartBeatPacketOrBuilder() {
        if ((payloadCase_ == 3) && (heartBeatPacketBuilder_ != null)) {
          return heartBeatPacketBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 3) {
            return (pipe.work.HeartBeatRPC.HeartBeatPacket) payload_;
          }
          return pipe.work.HeartBeatRPC.HeartBeatPacket.getDefaultInstance();
        }
      }
      /**
       * <code>optional .HeartBeatPacket heartBeatPacket = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.work.HeartBeatRPC.HeartBeatPacket, pipe.work.HeartBeatRPC.HeartBeatPacket.Builder, pipe.work.HeartBeatRPC.HeartBeatPacketOrBuilder> 
          getHeartBeatPacketFieldBuilder() {
        if (heartBeatPacketBuilder_ == null) {
          if (!(payloadCase_ == 3)) {
            payload_ = pipe.work.HeartBeatRPC.HeartBeatPacket.getDefaultInstance();
          }
          heartBeatPacketBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pipe.work.HeartBeatRPC.HeartBeatPacket, pipe.work.HeartBeatRPC.HeartBeatPacket.Builder, pipe.work.HeartBeatRPC.HeartBeatPacketOrBuilder>(
                  (pipe.work.HeartBeatRPC.HeartBeatPacket) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 3;
        onChanged();;
        return heartBeatPacketBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.work.VoteRPC.VoteRPCPacket, pipe.work.VoteRPC.VoteRPCPacket.Builder, pipe.work.VoteRPC.VoteRPCPacketOrBuilder> voteRPCPacketBuilder_;
      /**
       * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
       */
      public boolean hasVoteRPCPacket() {
        return payloadCase_ == 4;
      }
      /**
       * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
       */
      public pipe.work.VoteRPC.VoteRPCPacket getVoteRPCPacket() {
        if (voteRPCPacketBuilder_ == null) {
          if (payloadCase_ == 4) {
            return (pipe.work.VoteRPC.VoteRPCPacket) payload_;
          }
          return pipe.work.VoteRPC.VoteRPCPacket.getDefaultInstance();
        } else {
          if (payloadCase_ == 4) {
            return voteRPCPacketBuilder_.getMessage();
          }
          return pipe.work.VoteRPC.VoteRPCPacket.getDefaultInstance();
        }
      }
      /**
       * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
       */
      public Builder setVoteRPCPacket(pipe.work.VoteRPC.VoteRPCPacket value) {
        if (voteRPCPacketBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          voteRPCPacketBuilder_.setMessage(value);
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
       */
      public Builder setVoteRPCPacket(
          pipe.work.VoteRPC.VoteRPCPacket.Builder builderForValue) {
        if (voteRPCPacketBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          voteRPCPacketBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
       */
      public Builder mergeVoteRPCPacket(pipe.work.VoteRPC.VoteRPCPacket value) {
        if (voteRPCPacketBuilder_ == null) {
          if (payloadCase_ == 4 &&
              payload_ != pipe.work.VoteRPC.VoteRPCPacket.getDefaultInstance()) {
            payload_ = pipe.work.VoteRPC.VoteRPCPacket.newBuilder((pipe.work.VoteRPC.VoteRPCPacket) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 4) {
            voteRPCPacketBuilder_.mergeFrom(value);
          }
          voteRPCPacketBuilder_.setMessage(value);
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
       */
      public Builder clearVoteRPCPacket() {
        if (voteRPCPacketBuilder_ == null) {
          if (payloadCase_ == 4) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 4) {
            payloadCase_ = 0;
            payload_ = null;
          }
          voteRPCPacketBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
       */
      public pipe.work.VoteRPC.VoteRPCPacket.Builder getVoteRPCPacketBuilder() {
        return getVoteRPCPacketFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
       */
      public pipe.work.VoteRPC.VoteRPCPacketOrBuilder getVoteRPCPacketOrBuilder() {
        if ((payloadCase_ == 4) && (voteRPCPacketBuilder_ != null)) {
          return voteRPCPacketBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 4) {
            return (pipe.work.VoteRPC.VoteRPCPacket) payload_;
          }
          return pipe.work.VoteRPC.VoteRPCPacket.getDefaultInstance();
        }
      }
      /**
       * <code>optional .VoteRPCPacket voteRPCPacket = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.work.VoteRPC.VoteRPCPacket, pipe.work.VoteRPC.VoteRPCPacket.Builder, pipe.work.VoteRPC.VoteRPCPacketOrBuilder> 
          getVoteRPCPacketFieldBuilder() {
        if (voteRPCPacketBuilder_ == null) {
          if (!(payloadCase_ == 4)) {
            payload_ = pipe.work.VoteRPC.VoteRPCPacket.getDefaultInstance();
          }
          voteRPCPacketBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pipe.work.VoteRPC.VoteRPCPacket, pipe.work.VoteRPC.VoteRPCPacket.Builder, pipe.work.VoteRPC.VoteRPCPacketOrBuilder>(
                  (pipe.work.VoteRPC.VoteRPCPacket) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 4;
        onChanged();;
        return voteRPCPacketBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.work.Ping.PingMessage, pipe.work.Ping.PingMessage.Builder, pipe.work.Ping.PingMessageOrBuilder> trivialPingBuilder_;
      /**
       * <code>optional .PingMessage trivialPing = 5;</code>
       */
      public boolean hasTrivialPing() {
        return payloadCase_ == 5;
      }
      /**
       * <code>optional .PingMessage trivialPing = 5;</code>
       */
      public pipe.work.Ping.PingMessage getTrivialPing() {
        if (trivialPingBuilder_ == null) {
          if (payloadCase_ == 5) {
            return (pipe.work.Ping.PingMessage) payload_;
          }
          return pipe.work.Ping.PingMessage.getDefaultInstance();
        } else {
          if (payloadCase_ == 5) {
            return trivialPingBuilder_.getMessage();
          }
          return pipe.work.Ping.PingMessage.getDefaultInstance();
        }
      }
      /**
       * <code>optional .PingMessage trivialPing = 5;</code>
       */
      public Builder setTrivialPing(pipe.work.Ping.PingMessage value) {
        if (trivialPingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          trivialPingBuilder_.setMessage(value);
        }
        payloadCase_ = 5;
        return this;
      }
      /**
       * <code>optional .PingMessage trivialPing = 5;</code>
       */
      public Builder setTrivialPing(
          pipe.work.Ping.PingMessage.Builder builderForValue) {
        if (trivialPingBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          trivialPingBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 5;
        return this;
      }
      /**
       * <code>optional .PingMessage trivialPing = 5;</code>
       */
      public Builder mergeTrivialPing(pipe.work.Ping.PingMessage value) {
        if (trivialPingBuilder_ == null) {
          if (payloadCase_ == 5 &&
              payload_ != pipe.work.Ping.PingMessage.getDefaultInstance()) {
            payload_ = pipe.work.Ping.PingMessage.newBuilder((pipe.work.Ping.PingMessage) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 5) {
            trivialPingBuilder_.mergeFrom(value);
          }
          trivialPingBuilder_.setMessage(value);
        }
        payloadCase_ = 5;
        return this;
      }
      /**
       * <code>optional .PingMessage trivialPing = 5;</code>
       */
      public Builder clearTrivialPing() {
        if (trivialPingBuilder_ == null) {
          if (payloadCase_ == 5) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 5) {
            payloadCase_ = 0;
            payload_ = null;
          }
          trivialPingBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .PingMessage trivialPing = 5;</code>
       */
      public pipe.work.Ping.PingMessage.Builder getTrivialPingBuilder() {
        return getTrivialPingFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .PingMessage trivialPing = 5;</code>
       */
      public pipe.work.Ping.PingMessageOrBuilder getTrivialPingOrBuilder() {
        if ((payloadCase_ == 5) && (trivialPingBuilder_ != null)) {
          return trivialPingBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 5) {
            return (pipe.work.Ping.PingMessage) payload_;
          }
          return pipe.work.Ping.PingMessage.getDefaultInstance();
        }
      }
      /**
       * <code>optional .PingMessage trivialPing = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.work.Ping.PingMessage, pipe.work.Ping.PingMessage.Builder, pipe.work.Ping.PingMessageOrBuilder> 
          getTrivialPingFieldBuilder() {
        if (trivialPingBuilder_ == null) {
          if (!(payloadCase_ == 5)) {
            payload_ = pipe.work.Ping.PingMessage.getDefaultInstance();
          }
          trivialPingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pipe.work.Ping.PingMessage, pipe.work.Ping.PingMessage.Builder, pipe.work.Ping.PingMessageOrBuilder>(
                  (pipe.work.Ping.PingMessage) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 5;
        onChanged();;
        return trivialPingBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WorkMessage)
    }

    // @@protoc_insertion_point(class_scope:WorkMessage)
    private static final pipe.work.Work.WorkMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pipe.work.Work.WorkMessage();
    }

    public static pipe.work.Work.WorkMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<WorkMessage>
        PARSER = new com.google.protobuf.AbstractParser<WorkMessage>() {
      public WorkMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new WorkMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WorkMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WorkMessage> getParserForType() {
      return PARSER;
    }

    public pipe.work.Work.WorkMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WorkMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WorkMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024resources/work.proto\032 resources/Append" +
      "EntriesRPC.proto\032\034resources/HeartBeatRPC" +
      ".proto\032\027resources/VoteRPC.proto\032\024resourc" +
      "es/Ping.proto\"\337\001\n\013WorkMessage\022\025\n\runixTim" +
      "eStamp\030\001 \002(\003\0223\n\023appendEntriesPacket\030\002 \001(" +
      "\0132\024.AppendEntriesPacketH\000\022+\n\017heartBeatPa" +
      "cket\030\003 \001(\0132\020.HeartBeatPacketH\000\022\'\n\rvoteRP" +
      "CPacket\030\004 \001(\0132\016.VoteRPCPacketH\000\022#\n\013trivi" +
      "alPing\030\005 \001(\0132\014.PingMessageH\000B\t\n\007payloadB" +
      "\013\n\tpipe.work"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pipe.work.AppendEntriesRPC.getDescriptor(),
          pipe.work.HeartBeatRPC.getDescriptor(),
          pipe.work.VoteRPC.getDescriptor(),
          pipe.work.Ping.getDescriptor(),
        }, assigner);
    internal_static_WorkMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WorkMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WorkMessage_descriptor,
        new java.lang.String[] { "UnixTimeStamp", "AppendEntriesPacket", "HeartBeatPacket", "VoteRPCPacket", "TrivialPing", "Payload", });
    pipe.work.AppendEntriesRPC.getDescriptor();
    pipe.work.HeartBeatRPC.getDescriptor();
    pipe.work.VoteRPC.getDescriptor();
    pipe.work.Ping.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
